### ISSUE TITLE
(minor html display issue) <strong> tags in refs occasionally missing following space or line break

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/rootstock#155]
See [reference 30](https://greenelab.github.io/meta-review/v/ae1dd9ebd7b533b578041fd402217a73fd113899/#ref-QBWMEuxW) in meta review for an example. In some of the references, the `<strong>` (bold) part is missing a space or line break after it. As far as I can tell, this is a pandoc issue. Nothing in the markup, ref json, etc seems to cause this.

Very minor issue, but I can include a simple javascript fix (modifying the generated html) in the other scripts being added (for tooltips, highlighting, etc).

**Comment by slochower** [comment]
I would suspect this is an issue in our custom CSL style. Probably worth uploading the CSL here (http://editor.citationstyles.org/visualEditor/) and seeing how it handles the website container type with a missing author.

**Comment by agitter** [comment]
@slochower that makes sense.  I missed the fact that this problem was occurring within references.  In that case, it does not need to be reported to pandoc.

**Comment by vincerubinetti** [comment]
Yep, it's in the `style.csl`. I recommend changing `<layout>` to `<layout delimiter=" ">` to separate all the containing elements by a space, then change any first generation children of `<layout>` to have space-less prefixes/suffixes, eg `<text variable="citation-number" suffix=". "/>` to `<text variable="citation-number" suffix="."/>`. I think that makes more sense for how the layout is intended to be.

I'd make a pr but not sure whether to do it in `manubot-rootstock` or `meta-review` or both.

**Comment by agitter** [comment]
> I'd make a pr but not sure whether to do it in manubot-rootstock or meta-review or both.

Our general strategy for changes like this is to make the PR in manubot-rootstock.  Then we periodically update meta-review and all other Manubot manuscripts to pull in the upstream changes (e.g. https://github.com/greenelab/meta-review/pull/112).
