### ISSUE TITLE
Refactor file structure of bundling of css and js files in html output

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/rootstock#163]
Related to [#156](https://github.com/greenelab/manubot-rootstock/issues/156).

We are hotlinking `hypothesis`, embedding `anchorsjs`, and locally linking `github-pandoc.css`. We should decide on a consistent way to include these external dependencies. We should also provide an easy way for the user to toggle off these features, either with command line arguments or in a config file, or even simply by removing files from a folder.

**Comment by vincerubinetti** [comment]
I'm thinking we should have everything that can reasonably be embedded (html, javascript, css) be embedded. This provides some advantages:
1. Makes the html file totally self sufficient.
a. Allows offline access (useful for train rides into the city!).
b. Less confusing for users. Nothing to "carry around" along with the main `.html` file, except for the images (which I feel is intuitive enough for non-tech savvy people).
2. All rendered/produced versions from the past of a manuscript are guaranteed to work the same way as they did at the time, because they'll have the same version of the tooltips plugin, anchors plugin, etc.

**Comment by vincerubinetti** [comment]
Just checked Hypothesis

**Comment by dhimmel** [comment]
I agree that switching to option 1 (embedded js & css) makes sense for now. I think it is probably okay to continue loading hypothesis from its javascript URL (although let's weigh the pros and cons of this).

In the future, I think that we may want to to move the manubot CSS and JS files from rootstock into a centralized repository. Then users would only have to copy these files to their local manubot repo if they wanted to modify them. This approach would fit with simplifying rootstock. However, it is compatible with any of the options... i.e. we could always pull the CSS and JS files from URLs and embed them in the pandoc HTML output.

@agitter and @slochower: what do you think about switching to embedding all the CSS and JS required for the manubot's display into its HTML outputs? This would get rid of `pandoc-github.css` in the `webpage` directory/branch.

**Comment by agitter** [comment]
Option 1 "Javascript and CSS are embedded into manuscript.html" is okay with me.  These front end aspects are fairly foreign to me, so I only have mild opinions.  The advantages @vincerubinetti articulated make sense to me.

**Comment by vincerubinetti** [comment]
@slochower The css and js files would still be standalone files before building the manuscript, so the user could edit the themes/plugins to their content. What we are referring to is just how the files are integrated into the built `.html` file: whether they are left as standalone files in some other local folder, whether they are hosted online somewhere and linked to, or whether they are just copied and pasted right into the `.html` file itself. What I'm advocating for is the latter.

**Comment by dhimmel** [comment]
Sounds like there aren't any objections. So @vincerubinetti, go ahead with option 1 where all CSS & JS is embedded from files in the `build/assets` directory.

We can then delete `webpage/github-pandoc.css` and remove the following lines:

https://github.com/greenelab/manubot-rootstock/blob/eb4cb3efef46af8bfff1e391853006777cef373c/build/webpage.py#L142-L146

**Comment by vincerubinetti** [comment]
Here is my proposed restructuring of the `/build` folder to what I think will be clearer for the user. Let's discuss.

**`/assets`**
- `pandoc-reference.docx` - needed for pandoc to export docx I assume?
- `redirect-template.html` - needed for pandoc I assume?

**`/themes`**:
- `default.css` - css only. default nice styling of pandoc html output. squashes tables to fit page width. moden, minimal, similar to [material design](https://www.google.com/search?q=material+design&oq=material+design&aqs=chrome..69i57j69i60l2j0l3.1823j0j7&sourceid=chrome&ie=UTF-8)
- `nih.css` - NIH grant style theme, per Casey's suggestion
- `academic.css` - typical "academic" paper style. serif font, two columns when printed
- `lens.css` - lens viewer looking theme. serif font, little more fancy/elegant looking. like ralph lauren or tommy hilfiger.

**`/plugins`**:
- `table-scroll.html` - js and css. allows tables that are too wide for page width to scroll instead of being squashed
- `tooltips.html` - js and css. provides tooltips when hovering citation links
- `toc.html` - js and css. some kind of menu that will provide table of contents with links to jump to sections
- `samerefs.html` - js and css. some kind of menu that will show other instances of the selected reference. might be combined with `toc.html` menu?
- `accordion.html` - js and css. will allow `h2` sections to be collapsed/expanded
- `anchors.html` - js and css. puts permalinks next to desired heading sections.
- `hypothesis.html` - js and css. adds side bar for annotations.
- `analytics.js` - js. adds google analytics or similar tracking

This way all these things are separate, and are also somewhat clear in their function just by virtue of their file names. Users can toggle these things on/off just by including/removing them in/from the `build.sh` command (or command line argument, or manubot config file, if we ever switch to either of those approaches).

It also might be good to separate these all into separate PRs as well.

**Comment by agitter** [comment]
If some or all of these resources are moving to the `manubot-resources` repository, does that mean that local manuscript builds will now require internet connectivity to access those resources? I may have missed some of that discussion.

**Comment by vincerubinetti** [comment]
@agitter Daniel and I talked about this. We were going to leave the basic icons here in `manubot-rootstock` as well, since they are included in the front matter template and we wanted people to be able to use those offline. I would assume we'll always include the basic/default things needed to build a manuscript in `rootstock`, like the default themes. But then we'll have some extra optional stuff in `manubot-resources` if users want to download it and use it, as noted in that repo's readme.

**Comment by vincerubinetti** [comment]
Closed by [pr #168](https://github.com/manubot/rootstock/pull/168)
