### ISSUE TITLE
Weasyprint doesn't properly squash wide tables

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/rootstock#173]
I just noticed that our test `delete-me.md` shows an error in the weasyprint export. Tables that are too wide to fit within the page simply overflow off the side. In Chrome's print to pdf this does not occur. I can't seem to specify any CSS that will fix the issue. It may have to do with weasyprint not supporting the commong `word-break` property, or with one of these issues:

https://github.com/Kozea/WeasyPrint/issues/695
https://github.com/Kozea/WeasyPrint/issues/727
https://github.com/Kozea/WeasyPrint/issues/663
https://github.com/Kozea/WeasyPrint/issues/541

I see that in the latest build of manubot (or pandoc?), we are using version 0.42.3 of weasyprint. Based on the above issues, it's possible that it might be fixed by switching to the latest version (0.43).

**Comment by dhimmel** [comment]
We specify the version of weasyprint at:

https://github.com/greenelab/manubot-rootstock/blob/ec359f63c7d2b9ec0f2c04fabccd648f0b6a1ab9/build/environment.yml#L31

**Comment by vincerubinetti** [comment]
Closing this as it seems like we're moving away Weasy Print.
