### ISSUE TITLE
Migrating repo to the manubot organization

### ISSUE THREAD

**Issue by dhimmel** [manubot/rootstock#175]
For those who aren't aware, we now control the @manubot GitHub username. We've set up a Manubot organization and would like to move all development to this organization.

In https://github.com/manubot/manubot/issues/94 / https://github.com/manubot/manubot/commit/1b3ac66de9220e0b7496128a4a45e444b6d4edb1 we moved the `greenelab/manubot` repo to `manubot/manbot`.

`manubot-rootstock` will be the most challenging repository to migrate, as we have to consider many factors. Here we'll discuss the migration plan.

Currently, we are thinking of moving `greenelab/manubot-rootstock` to `manubot/rootstock`. Here we'll catalog all the things that could break.

**Comment by dhimmel** [comment]
# Option 1

Use GitHub transfer repo option to relocate repo to `manubot/manubot-rootstock` and then rename to `manubot/rootstock`.

Will work:

+ git remote redirects
+ github redirects for issue / pr / commit / repo links
+ The following URLS all work:
    ```markdown
  
  https://github.com/greenelab/manubot/blob/15eae64dab2e88d97952a6f41baf2acdad91b72c/README.md
  https://github.com/greenelab/manubot/raw/15eae64dab2e88d97952a6f41baf2acdad91b72c/README.md
    # This one does not redirect to `manubot/manubot`
  https://raw.githubusercontent.com/greenelab/manubot/15eae64dab2e88d97952a6f41baf2acdad91b72c/README.md
    ```
    Therefore, links to the CSL style should still work (like [this one](https://github.com/manubot/manubot/blob/1b3ac66de9220e0b7496128a4a45e444b6d4edb1/manubot/command.py#L87)).

Will break:

+ Existing hyperlinks to GitHub Pages URLs in Manubot outputs.

**Comment by dhimmel** [comment]
# travis-ci.com

]It probably makes sense to switch from travis-ci.org to travis-ci.com for `manubot/rootstock`, which we discuss in https://github.com/greenelab/manubot-rootstock/pull/124: 

> New Manubot instances should use .com. However, this repo hasn't received the migration email yet. Therefore, if we switch the URLs to .com, the build links won't work.

Migrating this repo to a new account, actually offers us the ability to switch to .com, while keeping the old build links functional, which is a nice plus.

I believe the switch to travis-ci.com from travis-ci.org will also switch us from the "Legacy Webhooks integration" to the "GitHub-Apps based integration", which uses the [GitHub Checks API](https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com). I actually find the new design annoying as it takes an extra click to get to the actual build log (and this link is really small, boxed in red below):

> ![image](https://user-images.githubusercontent.com/1117703/52656500-8321aa00-2ec4-11e9-94fe-bed89dde45b8.png)

**Comment by dhimmel** [comment]
@agitter do you want to review https://github.com/greenelab/manubot-rootstock/pull/180, which assumes "Option 1" of transferring the repo and renaming to `manubot/rootstock`. My idea is that if we have this PR ready to go, we should be able to have little downtime after doing the transfer via GitHub's online interface.

**Comment by agitter** [comment]
I also find the Checks interface annoying, but I do support the move.  I'll review #180.

**Comment by dhimmel** [comment]
Okay I am going to perform the migration now.

**Comment by dhimmel** [comment]
Looks like everything worked as intended. If not let us know!

**Comment by slochower** [comment]
Well done, thanks all.
