### ISSUE TITLE
Enhancement: Allow user to specify favicon

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/rootstock#181]
It might be nice to allow the user to specify one of the images in their `/images` folder as the favicon for their generated `manuscript.html`, either as an `.ico` file, or a regular `.png`/`.jpg`/etc (which we'd have to convert to `.ico`). We could provide a couple of nice favicon options in the `manubot/resources`, like a manuscript/scroll icon, or a science-y looking graph/web icon.

So, when someone bookmarks a manuscript made with manubot, they'd see a nice, descriptive icon, instead of the browser generic icon like this:

![image](https://user-images.githubusercontent.com/8326331/53349227-abf56680-38ea-11e9-9e79-ca1681e25702.png)

The value this provides is very minor, so maybe we can consider it after all the bigger things are done.

**Comment by dhimmel** [comment]
In https://github.com/manubot/rootstock/issues/267, we're discussing using manuscript thumbnails as the manuscript favicon. I'd like to try this out on some of the existing [catalog](https://manubot.org/catalog/) thumbnails, to see if the large images work when displayed so small.

Would it be possible to include multiple favicon specification in the HTML such that if the thumbnail favicon is missing or not supported, a small manubot logo favicon will be used as a fallback?

**Comment by dhimmel** [comment]
We now set the favicon for manuscripts to the Manubot favicon:

https://github.com/manubot/rootstock/blob/2017d790a9b9b6d7231535d3f4f8ba6673c4c983/manuscript.html#L121-L122

Currently, we don't easily support setting a custom favicon, but I don't think any users would use this option at the moment. So I will close this issue, but if a user wants to set a custom favicon we can reopen this issue and implement it.
