### ISSUE TITLE
`git --work-tree=webpage checkout gh-pages -- v` logs error for new manuscripts

### ISSUE THREAD

**Issue by slochower** [manubot/rootstock#183]
This is a followup to #182. That PR fixed the failure to build `psutil` on a manuscript I cloned from `rootstock` two days ago. However, something is still not quite right. In the Travis output, I see:

```
Your branch is up to date with 'origin/master'.
Agent pid 5233
Identity added: ci/deploy.key (ci/deploy.key)
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
From github.com:slochower/paprika-manuscript
 * [new branch]      gh-pages   -> gh-pages
 * [new branch]      output     -> output
 * [new branch]      gh-pages   -> origin/gh-pages
 * [new branch]      output     -> origin/output
Attempting checkout with the following command:
git --work-tree=webpage checkout gh-pages -- v
Checkout returned a nonzero exit status. See stderr:
error: pathspec 'v' did not match any file(s) known to git.
```
...and via email:
```
The page build failed for the `gh-pages` branch with the following error:

Unable to build page. Please try again later.

For information on troubleshooting Jekyll see:

 https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
``` 

The error is coming from:
https://github.com/manubot/rootstock/blob/717630e7fa73f0388f1de9231db4f90f1e984888/build/webpage.py#L86-L107

Is that lone `v` correctly placed to pull out the correct version? Do we need a `mkdir` for new manuscripts?

Build log: https://api.travis-ci.com/v3/job/181325550/log.txt

**Comment by dhimmel** [comment]
Could this be because the `gh-pages` branch doesn't contain a `v` directory yet, because there haven't been any successful deployments? IIRC, it was difficult to implement this in such a way to be more graceful when `v` didn't exist yet.

I think you can safely ignore the `pathspec 'v' did not match any file(s) known to git`. Once it gets created, you will no longer see this message. Note that your builds will not fail due to this.

**Comment by agitter** [comment]
If this is expected behavior when setting up new manuscripts, we should document it in `SETUP.md`.  The email notification of an error will make users think there is a problem.

**Comment by dhimmel** [comment]
> If this is expected behavior when setting up new manuscripts, we should document it in `SETUP.md`.

I believe the Travis log will contain `pathspec 'v' did not match any file(s)` for the first deploy only, so it's a rather niche scenario.

> The email notification of an error will make users think there is a problem.

I don't think the email is related. That seems like an error in the [GitHub Pages build](https://help.github.com/en/articles/troubleshooting-github-pages-builds). Manubot doesn't have GitHub Pages do any sort of extensive build. My guess is that this could be an intermittent GitHub Pages error.

**Comment by slochower** [comment]
> I don't think the email is related. That seems like an error in the [GitHub Pages build](https://help.github.com/en/articles/troubleshooting-github-pages-builds). Manubot doesn't have GitHub Pages do any sort of extensive build. My guess is that this could be an intermittent GitHub Pages error.

Maybe we can spin up a few dummy manuscripts from time to time to test the entire integration workflow and see if any errors pop up.
