### ISSUE TITLE
Manubot introduction video

### ISSUE THREAD

**Issue by agitter** [manubot/rootstock#200]
@slochower made a 2 minute video introducing Manubot and editing through the GitHub interface in https://github.com/greenelab/meta-review/issues/139.  Do we want to use that anywhere else to promote and explain Manubot?  Maybe the readme here?

The video is on Figshare: https://doi.org/10.6084/m9.figshare.7946192.v1

**Comment by vincerubinetti** [comment]
As a heads up my intent is to eventually have:

- short gifs of specific functionality
- longer-form tutorial videos like this one, with polished recording and other production values (I have good microphones and soundproofing from my past as a composer/producer and I have experience with After Effects for the video editing)
- exhaustive docs

And I guess these would all be linked on the landing page. In the interim, I'd say use it wherever you want, with the knowledge that it'll probably be replaced (and superseded, in the sense that the info/look/functionality that's shown in the video now may be slightly different later).

**Comment by dhimmel** [comment]
I think we should add it to the README of try-manubot (and probably to the manuscript body there as well). Personally regarding Rootstock, I think it belongs more in USAGE.md than in the README.md.
