### ISSUE TITLE
clickClose=true and keepHorizontal=true tooltip position bug

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/rootstock#202]
In the tooltip plugin, with options `clickClose=true` and `keepHorizontal=true`, hovering from one citation to another will keep the horizontal position of the tooltip. The `keepHorizontal` behavior is really only intended for when the user clicks the `<` / `>` buttons in the tooltip, and nothing else (not even the left/right arrow keys).

I know the issue in the code. It is a regression. Also a relatively easy fix. Will fix soon.

**Comment by vincerubinetti** [comment]
The cleanest way to solve this is to remove the keepHorizontal option all-together. I'm not sure it was a user-friendly behavior in the first place, as I think the tooltip should go directly over the link it is referring to, even if it means moving the tooltip away from the mouse semi-inconveniently. Users can always use the arrow keys to jump conveniently to prev/next.

**Comment by dhimmel** [comment]
I am okay with removing the keepHorizontal option. I do think it is a helpful way to allow viewers to quickly navigate through all citations of a selected reference. While the arrow keys are even more effective at this task, viewers may be unaware of this key binding. That being said, it's a relatively minor inconvenience to have the tooltip jump around horizontally, so if the implementation is ugly, then :hocho: it. @vincerubinetti your call on this.
