### ISSUE TITLE
Inline citation ordering not as expected

### ISSUE THREAD

**Issue by slochower** [manubot/rootstock#206]
https://github.com/manubot/rootstock/blob/091ca8d85c8ef2d7af16fcc8d2ed3ebcbc187f13/build/assets/style.csl#L38-L40

My understanding is these lines should sort inline citations like `[8, 9, 10, 11]` but I have a manuscript where the citations appear `[10, 11, 8, 9]` (https://slochower.github.io/smirnoff-host-guest-manuscript/v/a2fec1ee6bf387a1e664186f8ddd2c15facadcf7/). I'm not sure why this is the case.

I attempted to confirm the proper behavior in the Visual CSL Editor, but note: uploading the bundled `build/assets/style.csl` to the Visual CSL Editor for experimentation results in "Citeproc exception: TypeError: blob.strings is undefined". I haven't investigated the meaning of that error.

Also, this URL does not resolve:
https://github.com/manubot/rootstock/blob/091ca8d85c8ef2d7af16fcc8d2ed3ebcbc187f13/build/assets/style.csl#L7

**Comment by dhimmel** [comment]
> My understanding is these lines should sort inline citations like `[8, 9, 10, 11]` but I have a manuscript where the citations appear `[10, 11, 8, 9]`

I wonder if this behavior is related to http://docs.citationstyles.org/en/stable/specification.html#sorting

> `cs:citation` and `cs:bibliography` may include a `cs:sort` child element before the cs:layout element to specify the sorting order of respectively cites within citations, and bibliographic entries within the bibliography. In the absence of `cs:sort`, cites and bibliographic entries appear in the order in which they are cited.

**Comment by slochower** [comment]
> I wonder if this behavior is related to http://docs.citationstyles.org/en/stable/specification.html#sorting

But we do have `<sort>` before `<layout>`. 

> @slochower I am not sure why the order in your manuscript is not [9, 10, 8, 11], because 8 is the only work that has been cited prior in the text.

Why wouldn't you expected 8 to be the first (followed by 9, 10, and then 11)? Maybe I'm misunderstanding the sorting.

**Comment by dhimmel** [comment]
The [input](https://github.com/slochower/smirnoff-host-guest-manuscript/blob/a2fec1ee6bf387a1e664186f8ddd2c15facadcf7/content/02.main-text.md) is:

> `A complete description of the APR method has been characterized in the literature [@doi:10.1021/acs.jctc.5b00405; @doi:10.1002/jcc.23398; @doi:10.1007/s10822-014-9735-1; @doi:10.1021/ct5004109]`.

The output is:

> A complete description of the APR method has been characterized in the literature [10,11,8,9].

However, this output corresponds to:
```
@doi:10.1007/s10822-014-9735-1; @10.1021/ct5004109; @doi:10.1021/acs.jctc.5b00405; @doi:10.1002/jcc.23398
```

So the input order is not preserved as I had assumed. Instead what I think is happening is that the citations are being sorted as strings rather than numbers!

**Comment by slochower** [comment]
>  Instead what I think is happening is that the rendered citations are being sorted as strings rather than numbers!

Ah, good insight!  

Wonder if I could be related to something with `pandoc-citeproc` not recognizing the strings as numeric: https://github.com/jgm/pandoc-citeproc/issues/208

**Comment by adam3smith** [comment]
Yes, this appears to be the result of poorly written specifications and pandoc-citeproc reading them overly literally: `citation-number` is, for reasons I'm uncertain about, not listed as a number variable and should, as per the specs, therefore be parsed as a string during sort. That's obviously nonsense, though, and citeproc-js (and I assume most/all other processors) treat it as an integer when sorting. I'd appeal to John to change pandoc-citeproc's behavior though, even though very technically it is correct.

cc @rmzelle who may know more on why this wasn't included as a number.

**Comment by slochower** [comment]
Looping in @jgm. Is it intentional that `pandoc-citeproc` treats `citation-number` as a string and not an integer, and therefore sorts `citation-number` alphabetically?

**Comment by dhimmel** [comment]
> citation-number is, for reasons I'm uncertain about, not listed as a number variable and should, as per the specs, therefore be parsed as a string during sort.

@adam3smith are you referencing [these lines](https://github.com/citation-style-language/schema/blob/b8042c1ceb689c533f7178e6340663f55762f410/csl-data.json#L278-L280) in the `csl-data.json` schema?

**Comment by adam3smith** [comment]
I was looking at the [corresponding section in the specifications](http://docs.citationstyles.org/en/stable/specification.html#standard-variables) but that's just a different way of looking at the same thing, yes.

**Comment by jgm** [comment]
David Slochower <notifications@github.com> writes:

> Looping in @jgm. Is it intentional that `pandoc-citeproc` treats `citation-number` as a string and not an integer, and therefore sorts `citation-number` alphabetically?

Not intentional on my part.  (This is part of code I
inherited.)  It can be fixed; please submit an issue
requset on jgm/pandoc-citeproc.

**Comment by slochower** [comment]
(This is fixed upstream.)
