### ISSUE TITLE
Aesthetics: add space (or other punctuation) between title and container-title in CSL

### ISSUE THREAD

**Issue by slochower** [manubot/rootstock#218]
I think there should be a space between `container-title` and `title`, if there are no authors or publication. For example, this is how I see GitHub citations rendered:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5393995/57183426-d40cc300-6e61-11e9-8c53-b8cfcea0f1dd.png">

<img width="767" alt="image" src="https://user-images.githubusercontent.com/5393995/57183429-dff88500-6e61-11e9-86f4-83b13b72847f.png">

The JSON returned from GitHub looks like:
```json
  {
    "type": "webpage",
    "title": "Remove generics, add hydrogen radii, rename ffxml files by davidlmobley · Pull Request #101 · openforcefield/openforcefield",
    "container-title": "GitHub",
    "abstract": "This PR will:\n\n Remove generic atoms matching any element from smirnoff99Frosst so exceptions are raised if parameters are assigned to a molecule which contains an element we don&#39;t cover (osmiu...",
    "URL": "https://github.com/openforcefield/openforcefield/pull/101",
    "language": "en",
    "accessed": {
      "date-parts": [
        [
          "2019",
          5,
          4
        ]
      ]
    },
    "id": "cT3I9uDT"
  },
```

**Comment by slochower** [comment]
I think this maybe happens because there's only a group delimiter between author and venue, not title and venue, and if author is missing, perhaps this delimiter is skipped.


https://github.com/manubot/rootstock/blob/8d74236e1083be9b2814db084d59007ceb47d4a7/build/assets/style.csl#L48-L62

**Comment by agitter** [comment]
I agree this should be changed.  @vincerubinetti is this the same issue that #158 fixes?

**Comment by slochower** [comment]
Ah, yes. Perhaps this will be fixed by #158 by setting a `" "` delimiter between all fields, I think.

**Comment by vincerubinetti** [comment]
@agitter I believe so! cc @dhimmel for review of #158

**Comment by dhimmel** [comment]
I think it is possible that https://github.com/dhimmel/manubot-rootstock/commit/12b478389a2557aae3d1e941dd48a79cdd9507e1 and #158 will both fix this issue. Let me open a PR for https://github.com/dhimmel/manubot-rootstock/commit/12b478389a2557aae3d1e941dd48a79cdd9507e1, which we have already included partially in https://github.com/greenelab/meta-review/pull/216. The issue with changes to our CSL is that we don't have good tests. Therefore, I sometimes worry that when we fix one thing, we may break something else.
