### ISSUE TITLE
Links don't wrap correctly

### ISSUE THREAD

**Issue by Benjamin-Lee** [manubot/rootstock#224]
In the rendered HTML, wrapping does not preserve words inside of links. For example:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/13618205/58773408-f55cee00-858a-11e9-9657-74c25c7c42ac.png">

**Comment by agitter** [comment]
Cross referencing related discussion in https://github.com/greenelab/deep-review/pull/951

**Comment by dhimmel** [comment]
@vincerubinetti any solutions you can think of that would be better than the current behavior, which causes this odd wrapping within short words / citation numbers?

**Comment by vincerubinetti** [comment]
@Benjamin-Lee Can you provide a link to the html output for convenience, if possible? 

You're not talking about the pdf export by saying "rendering HTML" are you?

**Comment by dhimmel** [comment]
Quoting from https://github.com/greenelab/deep-review/pull/951#issuecomment-498260768

> To clarify on this, there is no CSS way to apply a certain style to an element based on the text it contains. In other words, if you want to wrap based on the length of the link text, or try to wrap if the link text appears to be a URL and not just a sentence, that will require javascript.

Would it make sense to default to no special wrapping rules for links, but then using JS to find long hyperlinks whose text is URL-like and then applying the wrap option to just those elements?

**Comment by dhimmel** [comment]
Note that we could also consider a class like `.wrap` that users could apply to problematic long URLs. Also use table context to wrap hyperlinked text in cells?

**Comment by dhimmel** [comment]
Talking with @vincerubinetti, the `word-break: break-all` that could be causing this may be fixed in the latest rootstock. Now it only applies to to table cells:

https://github.com/manubot/rootstock/blob/091ca8d85c8ef2d7af16fcc8d2ed3ebcbc187f13/build/themes/default.html#L224-L232

**Comment by vincerubinetti** [comment]
> Note that we could also consider a class like `.wrap` that users could apply to problematic long URLs. Also use table context to wrap hyperlinked text in cells?

A [`<wbr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) might be sufficient. Haven't used them before, so will have to look into their effectiveness.

**Comment by dhimmel** [comment]
The document where this is happening is https://benjamin-lee.github.io/deep-rules/v/e80c29cf64bbc0018edc9161e2483b33bea59225/#fig:overfitting-fig

**Comment by vincerubinetti** [comment]
> The document where this is happening is https://benjamin-lee.github.io/deep-rules/v/e80c29cf64bbc0018edc9161e2483b33bea59225/#fig:overfitting-fig

Yes, he's using an old version of the rootstock. Inspect the link in question and you'll see `word-break: break-all;`

**Comment by agitter** [comment]
@Benjamin-Lee I'm closing this because the rootstock update in https://github.com/Benjamin-Lee/deep-rules/pull/191 resolved the issue

In https://benjamin-lee.github.io/deep-rules/v/f73d7e8166957b92d0934b327614940d1ae449ea/
![image](https://user-images.githubusercontent.com/3532898/59029743-b2b64280-8824-11e9-85b3-9bad2872fe63.png)
