### ISSUE TITLE
`build.sh` stops abruptly without error when docker is missing

### ISSUE THREAD

**Issue by michaelmhoffman** [manubot/rootstock#229]
```
(manubot) mhoffman@mhoffman2 ~/src/collab/rootstock
$ build/build.sh 
Retrieving and processing reference metadata
## INFO
Manuscript content parts:
00.front-matter
01.abstract
02.delete-me
90.back-matter
## INFO
8 unique citations strings extracted from text
8 unique standard citations    
## INFO
requests-cache starting with 10 cached responses
## INFO
requests-cache finished with 10 cached responses
## INFO
Using UTC timezone.
Dating manuscript with the current datetime: 2019-06-06T20:52:02.890987+00:00
## INFO
Reading user-provided templating variables complete:
{}
## INFO
Generated manscript stats:
{
  "reference_counts": {
    "doi": 2,
    "isbn": 1,
    "pmcid": 1,
    "pmid": 1,
    "url": 2,
    "wikidata": 1,
    "total": 8
  },
  "word_count": 1194
}
Exporting HTML manuscript

(manubot) mhoffman@mhoffman2 ~/src/collab/rootstock [1]
$ echo $?
1
```

I expected to get a PDF.

I assume it is ending early because I don't have `docker` on my path.

**Comment by dhimmel** [comment]
Interesting. On the systems we tested on, the following line worked when docker was missing:

https://github.com/manubot/rootstock/blob/b9e1d42b51a1b6a2807ce82840c49f1791f65ac5/build/build.sh#L53-L54

It would return nothing. But assuming that https://github.com/manubot/rootstock/pull/230 fixes the issue for you, it looks like

```
`command -v docker`
```

doesn't work on your system. What OS were you using and what terminal?

**Comment by michaelmhoffman** [comment]
@agitter's explains in #230 how `set -o errexit` causes an abrupt termination here.

**Comment by dhimmel** [comment]
@michaelmhoffman confirming the issue occurred on windows, where presumably the `command` command does not exist?

**Comment by dongbohu** [comment]
To elaborate the issue, on a system that doesn't have `docker` installed, the return code of 
```
DOCKER_EXISTS=`command -v docker` 
``` 
is 1, which is an error, so the program will terminate due to `set -o errexit` at the beginning of `build.sh`.

**Comment by dhimmel** [comment]
Thanks @dongbohu for your explanation. Until now, I misunderstood this issue. Now I understand that `command -v docker` returns a nonzero exit code when `docker` does not exist, which is a BIG PROBLEM.  Seems like the fix in https://github.com/manubot/rootstock/pull/230 is therefore the right fix.

Bigger picture, it would be great to get better error messages when the script exits because of a nonzero exit code. For example, is it possible to get some sort of stacktrace like "exiting build.sh because line 54 returned a nonzero exit code"? Currently, it is extremely unclear what is going on! Thanks @michaelmhoffman for tracking it down.

**Comment by dongbohu** [comment]
Instead of use `set -o errexit`, use `set -o errexit -o xtrace`, or simply `set -ex`. The `xtrace` option will print out each command executed followed by error, if any.

**Comment by dhimmel** [comment]
I reran a build with `set -o errexit -o xtrace`. The following output is produced:

```
sh build/build.sh
+ export TZ=Etc/UTC
+ export LC_ALL=en_US.UTF-8
+ echo Retrieving and processing reference metadata
Retrieving and processing reference metadata
+ manubot process --content-directory=content --output-directory=output --cache-directory=ci/cache --log-level=INFO
## INFO
Manuscript content parts:
00.front-matter
01.abstract
02.introduction
03.results
04.discussion
05.methods
059.declarations
06.suppmaterial
90.back-matter
## INFO
41 unique citations strings extracted from text
41 unique standard citations    
## INFO
requests-cache starting with 155 cached responses
## INFO
requests-cache finished with 155 cached responses
## INFO
Using UTC timezone.
Dating manuscript with the current datetime: 2019-06-07T15:44:33.661843+00:00
## INFO
Reading user-provided templating variables complete:
{}
## INFO
Generated manscript stats:
{
  "reference_counts": {
    "doi": 36,
    "raw": 1,
    "url": 4,
    "total": 41
  },
  "word_count": 11211
}
+ CSL_PATH=build/assets/style.csl
+ BIBLIOGRAPHY_PATH=output/references.json
+ INPUT_PATH=output/manuscript.md
+ mkdir -p output
+ echo Exporting HTML manuscript
Exporting HTML manuscript
+ pandoc --verbose --from=markdown --to=html5 --filter=pandoc-fignos --filter=pandoc-eqnos --filter=pandoc-tablenos --bibliography=output/references.json --csl=build/assets/style.csl --metadata link-citations=true --include-after-body=build/themes/default.html --include-after-body=build/plugins/table-scroll.html --include-after-body=build/plugins/anchors.html --include-after-body=build/plugins/accordion.html --include-after-body=build/plugins/tooltips.html --include-after-body=build/plugins/jump-to-first.html --include-after-body=build/plugins/link-highlight.html --include-after-body=build/plugins/table-of-contents.html --include-after-body=build/plugins/lightbox.html --mathjax --variable math= --include-after-body=build/plugins/math.html --include-after-body=build/plugins/hypothesis.html --include-after-body=build/plugins/analytics.html --output=output/manuscript.html output/manuscript.md
+ command -v docker
+ DOCKER_EXISTS=/usr/bin/docker
+ [  != false ]
+ [ -z /usr/bin/docker ]
+ [  != false ]
+ [ -n /usr/bin/docker ]
+ echo Exporting PDF manuscript using Docker + Athena
Exporting PDF manuscript using Docker + Athena
+ [ -d output/images ]
+ cp -R -L content/images output/
+ pwd
+ docker run --rm --shm-size=1g --volume=/home/dhimmel/Documents/greene/manu-vgsv/output:/converted/ --security-opt=seccomp:unconfined arachnysdocker/athenapdf:2.16.0 athenapdf --delay=2000 manuscript.html manuscript.pdf
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Converted 'file:///converted/manuscript.html' to PDF: 'manuscript.pdf'
PDF Conversion: 5436.918ms
+ rm -rf output/images
+ [  = true ]
+ echo Build complete
Build complete
```

If I change build.sh to use `command -v dockermissing`, which will return a nonzero status, the output now ends with:

```
+ command -v dockermissing
+ DOCKER_EXISTS=
```

So @dongbohu this is not exactly what you have in mind. From [this page](https://www.linuxtechi.com/debugging-shell-scripts-in-linux/):

> The -x option, short for xtrace or execution trace, tells the shell to echo each command after performing the substitution steps. Thus , we can see the values of variables and commands. Often, this option alone will help to diagnose a problem.

We may want to consider setting this option for our build script (or at least our CI build), because it is helpful for seeing what the scripts do, but it doesn't solve the issue of better documentation of when a nonzero status causes an exit.

**Comment by dhimmel** [comment]
@agitter do you think we should set `-o xtrace` for `build.sh` and `deploy.sh`? This would increase log output, but we're already logging at the INFO level.

**Comment by agitter** [comment]
This level of logging seems somewhat excessive to me.  I'm not strongly opposed, but maybe there is another way we could be more explicit about errors.  https://www.davidpashley.com/articles/writing-robust-shell-scripts/ recommends

`command || { echo "command failed"; exit 1; }`

**Comment by dhimmel** [comment]
@agitter that is a helpful post. Seems like we might as well apply `set -o nounset` to require that variables are set, unless it interacts poorly with lines like:

https://github.com/manubot/rootstock/blob/aa09b789f53d0deea89c6d6ca563061c57bfed5b/build/build.sh#L57

Note to combine with [tip 12 here](https://kvz.io/blog/2013/11/21/bash-best-practices/).

Regarding appending `|| { echo "command failed"; exit 1; }`, I think this is a bit much to have it at the end of every line. Therefore, I'd lean more towards enabling `xtrace`.

**Comment by dhimmel** [comment]
I opened https://github.com/manubot/rootstock/pull/233 to make further improvements to the shell scripts.

> This level of logging seems somewhat excessive to me.

Since we're logging rather low level information from our `manubot process` and `pandoc` commands, I think it makes sense to log the shell scripts permissively. I see the benefits as much larger than the cost. Perhaps we should eventually consider ANSI codes to color log output so it's easy to spot warnings and errors.
