### ISSUE TITLE
merging adjacent table cells

### ISSUE THREAD

**Issue by sbonaretti** [manubot/rootstock#240]
Hi! Is there a way to merge to (horizontally) adjacent cells in a table?
Thanks!!!

**Comment by slochower** [comment]
I don't think this is possible until the upstream Markdown processor that `pandoc` uses, implements it. There is a very long thread discussing the possibility and implementation details: https://github.com/jgm/pandoc/issues/1024. I can't quite tell what the timescale is for this, but I'm confident that a lot of people care about this and the authors of `pandoc` seem to be taking it seriously.

**Comment by vincerubinetti** [comment]
Unfortunately the only way to accomplish this right now is to write out the table "manually" (in html) in your markdown, and use `colspan`, like this:

```HTML
<table>
 <tr>
  <td colspan="2">&nbsp;</td>
  <td>&nbsp;</td>
 </tr>
 <tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
 </tr>
 <tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
 </tr>
</table>
```
![image](https://user-images.githubusercontent.com/8326331/60444507-62e05680-9beb-11e9-93b5-c8eeff9fe3b0.png)


Reference:
https://www.computerhope.com/issues/ch001655.htm

**Comment by dhimmel** [comment]
> Unfortunately the only way to accomplish this right now is to write out the table "manually" (in html) in your markdown

@vincerubinetti are you sure the HTML table method works when passing through Pandoc? My understanding is that since Pandoc's Astract Syntax Tree doesn't support colspans, if the table gets interpreted by Pandoc, this solution won't work. However, I'm not sure whether Pandoc would interpret the table or just pass-through the HTML verbatim.

**Comment by vincerubinetti** [comment]
Just tested it, it does work. My understanding is that anything you write in plain HTML within a markdown file will just get passed through/ignored by pandoc. Is that consistent with your understanding?

**Comment by slochower** [comment]
It will pass through to the HTML output, but did you check that it also passes through to PDF and DOCX? That part I'm not sure about.

**Comment by vincerubinetti** [comment]
PDF output comes right from the HTML output, so as long as WeasyPrint/Athena supports `colspan`, it should work. As for `docx`, I don't know but I doubt it.

**Comment by slochower** [comment]
I think that writing the table as HTML will also break the functionality used by by `pandoc-tablenos`.

**Comment by sbonaretti** [comment]
I have finally tried this out. It works, and it was not hard. I opened the built `.html` and copied the table section to my `.md` file.   
I just have an issue now: In some cells I reference to the literature. The `md` command `@doi:something` becomes something like `<span class="citation" data-cites="aNdiyMUf">[<a href="#ref-aNdiyMUf" role="doc-biblioref">3</a>]</span>` in the `html`, which obviously does not reference to anything - and I get an error during the built. Is there an easy fix to this? Thanks!!!

**Comment by dhimmel** [comment]
> I opened the built .html and copied the table to my .md file.

Nifty solution. May be kind of a pain if you have to change the table or get table numbering to work, but cool to see the workaround.

> I get an error during the built.

Can you paste the error text?

> does not reference to anything

If Pandoc is still able to render the markdown in the HTML table cells, you could just revert the HTML citations back to the original citations. If you don't have too many citations in the table, it may just be easiest to do this manually. The `output/citations.tsv` file will show you the mapping from `manuscript_id` (e.g. `doi:something`) to `short_id` (e.g. `@aNdiyMUf`).

**Comment by vincerubinetti** [comment]
I have one solution. The others might have different solutions.

Instead of copying the html of the table into your input markdown, I'd just leave the table as regular markdown, and add the `colspan` attribute into the output itself. The downside of this, though, is that every time you re-build the output, that `colspan` change will go away. 

To solve this, we could create a plugin that looks for any cell that has some flag in commented-out text, say `<!-- colspan:2 -->`, and add the `colspan` html attribute to that cell dynamically. This should work for `html` output, and `pdf` output if Athena is being used (because it supports javascript).

**Comment by dhimmel** [comment]
> we could create a plugin that looks for any cell that has some flag in commented-out text

This is a cool idea. Won't work for DOCX outputs (but will an HTML table in a markdown input get converted to DOCX?).

@vincerubinetti happy for you to prototype this solution if you have time. If it works, we could include it as in the plugins directory (perhaps not added to the build command by default). I'm interested to see whether it works, and how general of a workaround it could be for "unsupported by pandoc" things.

**Comment by slochower** [comment]
Would be nice to look for a `<!-- colspan: 2 -->` attribute. That would be super helpful.

I'm fairly certain an HTML table embedded in Markdown will not get converted to DOCX with `pandoc`. I know that other HTML, like `<span class="red">this is red text</span> ` embedded in the Markdown get dropped going to DOCX.

**Comment by sbonaretti** [comment]
@dhimmel
>> Can you paste the error text?
Here it is: `ERROR: No anchor #aNdiyMUf for internal URI reference`  

I have noticed that: 
- If I cite the paper somewhere else in my text, the `HTML` line (`<span class="citation" data-cites="aNdiyMUf">[<a href="#ref-aNdiyMUf" role="doc-biblioref">3</a>]</span>`) works, i.e. I see the clickable link to the citation in the rendered `HTML`
- If I do NOT cite the paper somewhere else in my text, I get the error above 

Hope this helps
