### ISSUE TITLE
travis.com authentification problem

### ISSUE THREAD

**Issue by berceanu** [manubot/rootstock#246]
Following the instructions, I had trouble with this step:

```console
travis encrypt-file \
  --com \
  --repo=$OWNER/$REPO \
  --force \
  deploy.key > travis-encrypt-file.log
```

Seems the issue is already on [SO](https://stackoverflow.com/questions/36608870/travis-ci-encrypt-command-is-asking-for-login-pro), but basically I had to use `--org` instead of `--com`, and do `travis login --org` before `travis encrypt-file`.

**Comment by agitter** [comment]
Thanks for the report @berceanu.  Were you able to make it through the rest of the setup steps?  If you get stuck, we are working to simplify the setup in #243.  Those instructions eliminate the need to use the `travis` command line utility and instead use a Travis environment variable for authentication.

You raise a more general issue though.  This repository switched from travis-ci.org to travis-ci.com in #124.  Our setup instructions assume users are also configured to use travis-ci.com, but that isn't always the case.  We should see where we need to add workarounds or special case instructions for travis-ci.org projects.

**Comment by berceanu** [comment]
In my case I finished the setup with `travis.org`. However it did require some googling.

**Comment by dhimmel** [comment]
My understanding is that travis-ci.org is deprecated. The 2018 blog post [states](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps):

> If you’re activating a new repository – either public or private – on Travis CI, please use travis-ci.com. You’ll be able to take advantage of our newest features, and share additional concurrency between open source and private repositories.

See also [the migration docs](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg):

> Current users will keep both their travis-ci.com and travis-ci.org accounts at first. We recommend users of travis-ci.org activate any new repositories on travis-ci.com. If you have not signed up on travis-ci.com when you want to activate a new repository, please sign up there first.

> We should see where we need to add workarounds or special case instructions for travis-ci.org projects.

It seems like `.org` is on its way out... eventually these repos will be automatically migrated to `.com`. So IMO there isn't a reason to document how to set up with `.org`. @berceanu any reason you preferred `.org`?

**Comment by berceanu** [comment]
It's not that I prefer it, for me it was the only way to get `travis encrypt` working.

**Comment by dhimmel** [comment]
> It's not that I prefer it, for me it was the only way to get `travis encrypt` working.

Ah too bad. I've also found `travis encrypt` to be a struggle to use, and I'm never quite sure whether I need to put `--org` / `--com` or whether it can infer this. Anyways, after https://github.com/manubot/rootstock/pull/243 is merged, users will no longer need to use the travis gem... so I view that as the ultimate solution.
