### ISSUE TITLE
Special setup instructions for travis-ci.org

### ISSUE THREAD

**Issue by agitter** [manubot/rootstock#248]
After finishing #243, we should consider adding special instructions in the setup process for users that use travis-ci.org.  The settings pages appear similar so I expect adding the environment variable will work the same way in both cases.  Once difference may be how to activate continuous integrating testing on the new repository.  There also different badge URLs for the main and `ci` directory readmes.

Related to #246.

**Comment by dhimmel** [comment]
I am not in favor of this as per https://github.com/manubot/rootstock/issues/246#issuecomment-509292963. travis-ci.org is deprecated and not recommended for new repositories.

**Comment by agitter** [comment]
I may have confused the .org / .com issue with the legacy and newer GitHub App approaches for setting up a new repository.  My main goal would be to make sure that potential Manubot users don't get stuck at the Travis Ci setup steps if their interface doesn't match what the instructions describe.  We don't necessarily need to have two parallel sets of instructions for these steps, but acknowledging that some steps will vary if the user's Travis integration is different from ours could help prevents users from abandoning setup if it doesn't work.

**Comment by dhimmel** [comment]
We've updated the CI setup instructions considerably, and now Travis is not the default CI service, so I think this issue is less pertinent. Will close, but feel free to reopen if there are specific changes.
