### ISSUE TITLE
Updating Manubot: deploy keys merge conflict and double Travis builds

### ISSUE THREAD

**Issue by berceanu** [manubot/rootstock#253]
So when I do `git pull --no-ff --no-commit rootstock master` to update my [repo](https://github.com/berceanu/lwfa_scaling), I get two merge conflicts:

```
CONFLICT (modify/delete): ci/deploy.key.pub deleted in 2a5e425650947020d2d4b49447e3f3d9718dee40 and modified in HEAD. Version HEAD of ci/deploy.key.pub left in tree.
CONFLICT (modify/delete): ci/deploy.key.enc deleted in 2a5e425650947020d2d4b49447e3f3d9718dee40 and modified in HEAD. Version HEAD of ci/deploy.key.enc left in tree.
```

They both seem to be related to Travis CI, any hints on how to solve them?

**Comment by agitter** [comment]
@dhimmel saw this same conflict recently, which is due to the Travis CI-related updates made in this upstream `rootstock` repository.  Do his instructions in https://github.com/greenelab/meta-review/pull/251#issuecomment-509749375 work for you?  Specifically:
```
git checkout --ours ci/deploy.key.*
git add ci/deploy.key.*
```

**Comment by berceanu** [comment]
That fixed the merge conflict. I then did a PR but now Travis won't deploy anymore. Here's the full [log](https://api.travis-ci.com/v3/job/216456530/log.txt).

**Comment by agitter** [comment]
The deployment may actually be working even though Travis CI reports the build failed.  The permalink for the latest manuscript is https://berceanu.github.io/lwfa_scaling/v/1ec2360b2b028e31e7e8bb643b8c633b714b4c39/  This version was deployed today and contains the last commit from master, the typo fix in https://github.com/berceanu/lwfa_scaling/commit/1ec2360b2b028e31e7e8bb643b8c633b714b4c39

The Travis build may be failing now because of #250, which makes the build fail if the deploy step fails.  I'm not yet sure why the deploy step fails for your manuscript.  The [first build](https://travis-ci.com/berceanu/lwfa_scaling/builds/118092883#L807) and [most recent build](https://travis-ci.com/berceanu/lwfa_scaling/builds/119298229#L840) both contain the error:
`ci/deploy.sh: line 33: encrypted_5bcb62ac0f84_key: unbound variable`

**Comment by dhimmel** [comment]
This is the issue ([build](https://travis-ci.com/berceanu/lwfa_scaling/builds/119298229#L840)):

```
ci/deploy.sh: line 33: encrypted_5bcb62ac0f84_key: unbound variable
```

I don't see anything wrong with your merge commit (https://github.com/berceanu/lwfa_scaling/commit/2a31b68aaa76836f0b88a59d44a4ffdb61636559). The variable name of `encrypted_5bcb62ac0f84_key` seems to be the same as you initially set in https://github.com/berceanu/lwfa_scaling/commit/9a0d03c322ae8b08272abdea2fe0c7c876d6c238.

Is it possible you deleted the environment variable of `encrypted_5bcb62ac0f84_key` in the Travis settings?

Possibly the easiest solution at this point would be to switch to the new environment variable approach by doing the [steps here](https://github.com/manubot/rootstock/blob/2a5e425650947020d2d4b49447e3f3d9718dee40/SETUP.md#deploy-key)

**Comment by dhimmel** [comment]
> The deployment may actually be working even though Travis CI reports the build failed. 

AH! there are two builds

> ![image](https://user-images.githubusercontent.com/1117703/61293609-51717f80-a791-11e9-8c82-d40dfe03cf36.png)

**Comment by berceanu** [comment]
So what's the consensus then? I don't need to do anything?

**Comment by dhimmel** [comment]
I think you may have Travis CI installed twice, once at https://travis-ci.org/berceanu/lwfa_scaling/ and once at https://travis-ci.com/berceanu/lwfa_scaling/. The `.com` build is the one that failed. I'd go ahead and disable the `.com` Travis which hasn't been set up for deployment.

**Comment by berceanu** [comment]
Oh I see. I must have setup both during the initial configuration, ie I tried `.com`, that didnt work then I reverted to `.org`. How can I disable the `.com` now?

**Comment by dhimmel** [comment]
Probably [these steps](https://stackoverflow.com/a/50700205/4651668)

**Comment by agitter** [comment]
Those instructions look correct for the way I set up Travis CI.  The starting point is https://travis-ci.com/account/repositories.  Then you can get to the `Manage repositories on GitHub` button.

**Comment by berceanu** [comment]
Awesome, I completely disabled `.com` for all repos now :)

**Comment by agitter** [comment]
That's great.  I see there is only one build now and it passes:
![image](https://user-images.githubusercontent.com/3532898/61308605-336a4600-a7b6-11e9-8306-b1f3bb87d9fe.png)

I'll close this issue per your report that everything is fixed.
