### ISSUE TITLE
Tooltips plugin malfunctions when citation hidden in <details>

### ISSUE THREAD

**Issue by dhimmel** [manubot/rootstock#268]
@humbertodebat is leading a cool project to translate the Sci-Hub Coverage Study manuscript to spanish. We are keeping the English text but using the HTML `<details>` element to collapse it by default. [See manuscript here](https://greenelab.github.io/scihub-manuscript-es/v/353933ad77b02ebf578711ebb53f73752de55082/):

> ![image](https://user-images.githubusercontent.com/1117703/64880944-79f9e680-d627-11e9-82f5-8cd63f2a3e5c.png)

For future reference, we made some changes to the CSS to style the details in https://github.com/greenelab/scihub-manuscript-es/commit/56313e8811d392cbc12f4fc6f9cc822a5aef5d2b and https://github.com/greenelab/scihub-manuscript-es/commit/3a667f27c909db1916a912a13956969ed497080e.

Because we keep the english original in `<details>` (collapsed by default), each citation appears double. When using the tooltip extension to jump between other instances of the same citation, the tooltip goes away. @vincerubinetti is there a more natural way the extension could handle this?

**Comment by vincerubinetti** [comment]
You are referring to when you open a tooltip, then navigate to a prev/next instance of the same citation, and that next/prev citation happens to be inside a collapsed section.

There is no natural way to handle this. The tooltips plugin has to be updated to expand or show any hidden element it is focusing.

The relevant code is here:
https://github.com/manubot/rootstock/blob/master/build/plugins/tooltips.html#L425-L437

Note how it has to check if the new link it is focusing is within an accordion section, and expand it manually if it is.

**Comment by dhimmel** [comment]
Do either of these solutons make sense:

1. expand `<details>` like how an accordion is expanded when the next instance is contained in this section

2. skip over instances that cannot be expanded. for example, this could go from citation 1/4 to 3/4 because 2/4 was in collapsed details.

Both solutions would keep the tooltip active. The disappearance of the tooltip is the main issues IMO with the current situation.

**Comment by vincerubinetti** [comment]
Depends on the functionality you want. Either way, we should make it consistent for both accordion sections and details sections. Either expand on navigate or skip.

**Comment by dhimmel** [comment]
> we should make it consistent for both accordion sections and details sections. Either expand on navigate or skip.

expand on navigate seems like the best solution, since users often use the next button to browse every instance of a citation.
