### ISSUE TITLE
default CSS theme: only center the title header

### ISSUE THREAD

**Issue by dhimmel** [manubot/rootstock#273]
Currently all `<h1>` elements are centered due the following CSS:

https://github.com/manubot/rootstock/blob/6859ada7a28a72cd0ed728e085955f23fadc2b9a/build/themes/default.html#L70-L74

However, I am thinking that the only `h1` element that should be centered is the title, which pandoc denotes with `class="title"`. Previously this was never an issue because manuscripts usually only had a single h1 heading which was the title. However, from https://github.com/jgm/pandoc/issues/5071#issuecomment-438359609, it appears that pandoc recommends using h1 for the first level of headings (like abstract, introduction, references).

This has become an issue for https://github.com/manubot/manufesto/pull/3 where I switched abstract and such to h1 in order to improve the numbed sections. See what the centering of non-title h1 elements looks like in [manuscript-1.0.10-9cb98a6.pdf](https://github.com/manubot/rootstock/files/3752834/manuscript-1.0.10-9cb98a6.pdf).

@vincerubinetti what do you think?

**Comment by vincerubinetti** [comment]
I'm not sure. In the case of your Manufesto that you linked, I think the better solution is either to just make "Intro", "Abstract", and "Features" `<h2>`'s along with all the features, or move those down to `<h2>` and move all the features down to `<h3>` and make `<h3>`'s more visually distinct (maybe with an underline like the `<h2>`'s have.

We had talked about having `<h1>` centered for the title, and the very rare case of supplements. I don't think `<h1>`'s should be used liberally sorta like they are in that version of the Manufesto; they should be super big-picture, and very rare.

If we were to left align non-title `<h1>`'s, we'd also want to decrease their text size too; it looks too big in your Manufesto.

**Comment by dhimmel** [comment]
My markdown linter in vscode seems to agree that we shouldn't use h1 for section headings:

```
MD025/single-title/single-h1: Multiple top level headings in the same document markdownlint(MD025)
```

In https://github.com/manubot/manufesto/pull/3/commits/0fdde9c43142b272fe774f46b0c0db33c35988ce, I tried out the `--base-header-level=2` pandoc argument, such that we can type `# Abstract` in the markdown as suggested in https://github.com/jgm/pandoc/issues/5071#issuecomment-438359609, but have that render as h2. The title stays as h1.

> We had talked about having `<h1>` centered for the title, and the very rare case of supplements

Good point regarding supplements. I forgot about that use case.

Will update this issue with more final considerations, but for now thinking that I'll probably close as I think the Pandoc convention of using h1 for section headings is a bit misguided.

**Comment by agitter** [comment]
> the Pandoc convention of using h1 for section headings is a bit misguided.

That's my opinion as well.  h2 seems more appropriate for section headings, h1 for the main title and supplement title.

**Comment by Nebucatnetzer** [comment]
I can understand the reasoning behind this.
I noticed however that it introduces a problem with the TOC in the HTML as we can see in the example.
![Screenshot from 2019-12-22 22-56-52](https://user-images.githubusercontent.com/2287221/71327892-86d38380-250e-11ea-83df-7e1751a88f69.png)
