### ISSUE TITLE
deploy.sh error: Unbound variable

### ISSUE THREAD

**Issue by ChayaSt** [manubot/rootstock#278]
This is the first time I am trying to merge to master. All testes passed on the [PR](https://travis-ci.org/ChayaSt/fragmenter-manuscript/builds/612489953?utm_source=github_status&utm_medium=notification) but it fails to deploy once merged with this error:
https://travis-ci.org/ChayaSt/fragmenter-manuscript/builds/612492119#L835

Is there anything I need to change in my configuration?

**Comment by agitter** [comment]
Thanks for trying Manubot @ChayaSt.  This looks like it is related to the deploy key that Travis CI needs in order to write to the repository during the deploy step.  Did you encounter any problems during this step of the Manubot setup: https://github.com/manubot/rootstock/blob/master/SETUP.md#continuous-integration

**Comment by ChayaSt** [comment]
I set up Manubot a while ago and I do not recall encountering a problem. I can try it again.

**Comment by ChayaSt** [comment]
I followed the steps as described again (I already had the deploy key but created a new one in case there was something wrong with that one) and triggered the build again. It's still failing with the same error. However, I do see that the pdf and html did build.

**Comment by agitter** [comment]
This may be a https://travis-ci.org/ versus https://travis-ci.com/ issue.  At https://travis-ci.com/ChayaSt/fragmenter-manuscript/builds the builds are passing and the deploy appears to have worked: https://chayast.github.io/fragmenter-manuscript/

I believe we've seen this happen before, but I don't recall the solution.  Can you disable this repository at travis-ci.org and keep it enabled at travis-ci.com?

**Comment by ChayaSt** [comment]
OK. I did that. 
Thanks!
