### ISSUE TITLE
Hypothesis highlights appear in PDF export

### ISSUE THREAD

**Issue by dhimmel** [manubot/rootstock#280]
In https://github.com/greenelab/deep-review/pull/982#issuecomment-557165266, I noticed that a Hypothesis annotation appeared in the athenapdf PDF export of the HTML manuscript:

> ![image](https://user-images.githubusercontent.com/1117703/69357594-57053780-0c53-11ea-8fae-bb30f714dbae.png)

I believe this is occurring because we now set the rel=canonical link in the HTML `<head>`, so even though we're exporting the PDF from HTML at a local path, it's receiving the annotations from the web.

So I'm thinking we should disable hypothesis highlights for printing? @vincerubinetti what do you think?

**Comment by vincerubinetti** [comment]
> I believe this is occurring because we now set the rel=canonical link in the HTML `<head>`, so even though we're exporting the PDF from HTML at a local path, it's receiving the annotations from the web.

I don't think that's the issue. This shouldn't be happening. If I recall, I added some print-specific CSS to make sure the hypothesis highlights were invisible. They may have changed their class names. I'll look into it.

**Comment by vincerubinetti** [comment]
>  If I recall, I added some print-specific CSS to make sure the hypothesis highlights were invisible. 

Nevermind, apparently I didn't. I only hid the sidebar and the hypothesis highlight popup on print.

**Comment by milahu** [comment]
still an issue, when i combine hypothesis with [bindery](https://github.com/evnbr/bindery)

solution: hide the custom element

```css
    @media only print {
      hypothesis-sidebar {
        display: none !important;
      }
    }
```

**Comment by agitter** [comment]
Thanks for the report @milahu.  Is there a change you suggest for the Manubot rootstock `hypothesis.html` file, or does the upstream `embed.js` from Hypothesis need to be modified?

**Comment by milahu** [comment]
sorry, i confused this with the hypothesis issue tracker

its an upstream issue with hypothesis
