### ISSUE TITLE
Add background colours to cell

### ISSUE THREAD

**Issue by Nebucatnetzer** [manubot/rootstock#291]
Is there a known way to colourize cells in markdown?
I wasn't able to find one as of yet.

**Comment by dhimmel** [comment]
I don't think there is a way to do this in markdown. Also pandoc's abstract syntax tree probably doesn't support encoding cell color.

We have created a workaround for situations like this. The workaround, called the [`attributes` plugin](https://github.com/manubot/rootstock/blob/master/build/plugins/attributes.html), is a javascript tool that loads on the HTML output. Therefore, it won't work for outputs that aren't HTML (or derived from the HTML), such as DOCX.

Try putting the following inside a markdown cell:

```
<!-- $bgcolor="#ffb300" -->
```

If that doesn't work, then @vincerubinetti could probably give better advice than me.

**Comment by Nebucatnetzer** [comment]
Ah yes that is working, thank you :)

**Comment by vincerubinetti** [comment]
`bgcolor` looks like a deprecated attribute. The more modern (html5+) way to do this, and the more supported way going forward, is to use `style`, which is just CSS. So it would be:

```
<!-- $style="background: #ffb300;" -->
```
