### ISSUE TITLE
Default CSS headers

### ISSUE THREAD

**Issue by Nebucatnetzer** [manubot/rootstock#293]
I noticed that the headings sizes aren't correlating to the content.
E.g. an h5 heading is smaller than the caption of a table.
Since we should start with h2 the headers should be a bit bigger to not get so small when we use h5 as a level 4 heading.

**Comment by dhimmel** [comment]
Here is what github does:

# Heading 1

## Heading 2

### Heading 3

#### Heading 4

##### Heading 5

###### Heading 6

So it seems that GitHub does get smaller and smaller headings, eventually smaller than regular text.

> Since we should start with h2 the headers should be a bit bigger to not get so small when we use h5 as a level 4 heading.

I'm not sure I've ever had 4 levels of in-manuscript levels. When we're back from holidays, @vincerubinetti can perhaps suggest where to change the CSS to increase the level 5 heading size and see if he has any style suggestions.

**Comment by Nebucatnetzer** [comment]
The 4 levels happen because we had to use the project management phases in the document, otherwise 3 levels would be enough.
Smaller than the body text might be okay, what I find strange is that they are smaller than the captions which are usually footnote size?

**Comment by vincerubinetti** [comment]
Relevant:
https://stackoverflow.com/questions/55696808/why-do-h5-and-h6-have-smaller-font-sizes-than-p-in-most-user-agent-default

It is built into HTML/CSS itself, and is not related to Github specifically. It is a long-standing default styling, which I happen to think was a stupid choice. I'd be happy to break with precedence in this case.
