### ISSUE TITLE
Optimizing tables

### ISSUE THREAD

**Issue by Nebucatnetzer** [manubot/rootstock#294]
I tried now a lot of things but I can't seem to get it to work.
What I would like to do is to automatically adjust the column width to the content.
For example in this table:
https://nebucatnetzer.github.io/manubot_test/#tbl:projektziele
The columns "Ziel-Nr" and "Muss" don't need so much space. Does someone maybe have a tip for this?
Preferably I would like to set the table to 90% text width and divide that by the columns.

**Comment by Nebucatnetzer** [comment]
In the pandoc documentation I found something that helps a bit but requires a lot of manual adjustments. I'll write here if I find a better solution.
https://pandoc.org/MANUAL.html#tables

> If a pipe table contains a row whose printable content is wider than the column width (see --columns), then the table will take up the full text width and the cell contents will wrap, with the relative cell widths determined by the number of dashes in the line separating the table header from the table body. (For example ---|- would make the first column 3/4 and the second column 1/4 of the full text width.)

**Comment by Nebucatnetzer** [comment]
For the moment the easiest way to get the tables right is to generate them with the Markdown Table Generator but don't delete and of the dashes under the header because pandoc will create `<col style="width: 6%">` for each column matching the header dashes.

**Comment by agitter** [comment]
It looks like your workaround has the desired effect.  The current version of your linked table looks nice to me:
![image](https://user-images.githubusercontent.com/3532898/71477696-ff596f00-27b0-11ea-902b-01c9c057e238.png)

There is some additional discussion of tables in https://github.com/manubot/rootstock/issues/254 but that may not contain anything you don't already know.

**Comment by Nebucatnetzer** [comment]
Dammit, how did I miss that issue.
In HTML it's okay in the PDF it's still rubbish, I would now have to adjust the dashes to look okay in the PDF.
I'll check if the plugin mentioned in the other issue helps.

**Comment by dhimmel** [comment]
Ah yes, I see [the PDF](https://nebucatnetzer.github.io/manubot_test/v/d37d89c2e56c65b15b9c2925cf293a69d5d5c873/manuscript.pdf#page=6) column spacing is not ideal since the header gets excessively wrapped:

> ![image](https://user-images.githubusercontent.com/1117703/71482982-743da080-27d3-11ea-8b0a-edf0ed9b0a97.png)

**Comment by Nebucatnetzer** [comment]
I tried now with an additional attribute as mentioned in the other issue however that doesn't work in the PDF since it's a JavaScript solution.

**Comment by dhimmel** [comment]
> that doesn't work in the PDF since it's a JavaScript solution

FYI when creating PDFs via docker + athenapdf the javascript modifications to the HTML should load.

**Comment by Nebucatnetzer** [comment]
Ah okay, I tried again with a more obvious value and noticed that it doesn't work in the HTML either.
Strange, I used the same values from the other issue so they should work in theory.
https://nebucatnetzer.github.io/manubot_test/#projektziele

**Comment by vincerubinetti** [comment]
Closing this and deferring to #254 for all discussions about table column widths.
