### ISSUE TITLE
Mobile UI Issue

### ISSUE THREAD

**Issue by ben-heil** [manubot/rootstock#306]
When I open the page notes bar on the right side of the screen, the button to close the bar overlaps with the button to open the table of contents. As a result, closing the page notes/highlights bar opens the table of contents, which I then have to close to get back to reading.

Is it possible to disable the ToC button while the notes bar is expanded?

**Comment by agitter** [comment]
Thanks for reporting this. I'm able to reproduce it with the ready.mobi testing site.  The expanded Hypothesis sidebar sits behind the table of contents button:
![image](https://user-images.githubusercontent.com/3532898/73578836-45f05800-4446-11ea-8cf3-b8b0e3ab7f33.png)

Would it help if the table of contents button was instead behind the sidebar?  I don't know how to implement that.  Any ideas @vincerubinetti?

**Comment by dhimmel** [comment]
Crossreferencing other hypothesis issues in #281. One idea we've talked about in https://github.com/manubot/rootstock/issues/111#issuecomment-561874196 is not loading hypothesis by default, but having a button to activate it. I guess that wouldn't completely solve this issue, but could help.
