### ISSUE TITLE
Use js built-in "closest" function in plugins

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/rootstock#321]
I just found out about this [closest function](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest) that is built-in to javascript. I believe I have re-implemented the equivalent of this in several places in the plugins. We can probably simplify the code with this.

**Comment by dhimmel** [comment]
Ah nice find!

**Comment by vincerubinetti** [comment]
Unfortunately my function here

```javascript
function firstBefore(element, query) {
    while (element && element !== document.body && !element.matches(query))
      element = element.previousElementSibling || element.parentNode;

    return element;
  }
```

Doesn't do exactly what the built-in `closest` function does. `closest` seems to to go up parents, whereas mine goes through previous siblings and goes up parents only if it has to. Also not many code lines to save anyway.
