### ISSUE TITLE
GitHub Actions deployment not working?

### ISSUE THREAD

**Issue by srp33** [manubot/rootstock#331]
The rootstock instructions say to contact you. I'm probably doing something wrong, but here's my GitHub repository: https://github.com/srp33/ToolJig_manuscript Here's where I think I should be able to see the manuscript: https://srp33.github.io/ToolJig_manuscript/v/freeze/

Does this mean I need to follow the instructions for SSH Deploy Key setup? Or am I missing something?

Thanks!

**Comment by agitter** [comment]
Thanks for opening an issue @srp.  We definitely do want to know about deployment and setup issues.

I'm not seeing any obvious build or deployment errors in your latest build: https://github.com/srp33/ToolJig_manuscript/runs/597766069

Your [`gh-pages` branch](https://github.com/srp33/ToolJig_manuscript/tree/gh-pages) also looks good.

My current guess is that GitHub Pages is slow with the initial deployment or there is either a GitHub Pages setting that needs to be changed.  Does GitHub Pages show it is enabled at https://github.com/srp33/ToolJig_manuscript/settings?  The source should be `gh-pages branch` like
![image](https://user-images.githubusercontent.com/3532898/79638821-3af7ba80-814d-11ea-81b8-eea490827ea1.png)

**Comment by srp33** [comment]
@agitter Thanks for your quick reply. Yes, it shows the following:

![image](https://user-images.githubusercontent.com/12720/79639233-a9397e80-8147-11ea-8755-8cd73cf4a573.png)

Should I wait a bit to see if it shows up and then get back to you?

**Comment by dhimmel** [comment]
I think you need to do the following from [SETUP](https://github.com/manubot/rootstock/blob/073ce0e4e81c82e1ce8c55caeab0ebc6fd0f840c/SETUP.md#github-actions):

> If it does not work for you after completing this setup, try reselecting "gh-pages branch" as the Source for GitHub Pages in the repository Settings. GitHub Pages should now trigger on the next commit.

Sounds like you may have already reselected "gh-pages branch". If so, deployment should work upon the next commit (or perhaps if you reran the build for the latest commit).

Was hoping GitHub would fix this issue sooner rather than later. Perhaps we should make this part more clear in the documentation.

**Comment by srp33** [comment]
Thanks! I saw that but wasn't quite sure what it meant, so I ignored it (sorry!).

I just changed the branch to master and then changed it back to gh-pages. Then I made another commit. Now it's showing up. Thanks!
