### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by thorowitz** [manubot/rootstock#334]
The Manubot manuscript promises that

> The build process can also accommodate different “themes”, which change the general aesthetics and appearance of the exported document (e.g. from a contemporary sans-serif style to a more traditional serif style). 

Are there existing alternate themes available? Where would I find them?

**Comment by dhimmel** [comment]
Currently, we only have a single default HTML theme [available](https://github.com/manubot/rootstock/tree/073ce0e4e81c82e1ce8c55caeab0ebc6fd0f840c/build/themes). Multiple themes has been a common user request (see https://github.com/manubot/rootstock/issues/112), so we'd like to develop alternative themes in the future.

@thorowitz if there are specific tweaks you'd like to the theme, then let us know here. Many things are possible with small changes to [`build/themes/default.html`](https://github.com/manubot/rootstock/blob/073ce0e4e81c82e1ce8c55caeab0ebc6fd0f840c/build/themes/default.html). Happy to help you figure out how to tweak the theme to your needs.

**Comment by vincerubinetti** [comment]
Luckily changing the font is very easy. You can import online fonts, like [Google Fonts](https://fonts.google.com/), right at the top of `default.html` [like this](https://github.com/manubot/rootstock/blob/master/build/themes/default.html#L5-L6). Then to apply the font to everything, replace "Open Sans" on [this line](https://github.com/manubot/rootstock/blob/master/build/themes/default.html#L15) with your desired font name. You can put multiple fonts there, separated by comma, and for each character of text in your document, the browser will try the left-most font first, then try the next if the it isn't installed on the user's system or if it font doesn't have that particular text character, and so on.

**Comment by thorowitz** [comment]
I was able to change the font, as described. However, I have not been able to change the CSL style. I think the directions in comment #242 may be out of date. The `build.sh` file does not have the line `CSL_PATH=build/assets/style.csl `. Instead, it just loads the Pandoc defaults: `PANDOC_DEFAULTS_DIR="${PANDOC_DEFAULTS_DIR:-build/pandoc-defaults}"` (line 25). I tried altering the `pandoc-defaults`, but that failed for some unknown reason. Then I tried adding the CSL line to build.sh, right after the Pandoc default line: `CSL_PATH=https://www.zotero.org/styles/apa.csl`. But this had no effect on the output.

**Comment by agitter** [comment]
@thorowitz sorry about the outdated documentation.  The CSL behavior changed in #290.  Now the CSL style is specified in a pandoc defaults in [line 12 of the `common.yaml` file](https://github.com/manubot/rootstock/blob/073ce0e4e81c82e1ce8c55caeab0ebc6fd0f840c/build/pandoc-defaults/common.yaml#L12).

Is that the part of the Pandoc defaults you already tried editing?

Let's keep this issue open until we update the CSL information in `USAGE.md`.

**Comment by thorowitz** [comment]
Yes, I tried to edit common.yaml. It failed with `Process completed with exit code 64.`

**Comment by thorowitz** [comment]
Instead of pointing to a URL, I copied the app.csl file into my build/assets directory, and then changed Pandoc-defaults to point to that file. Success!

**Comment by dhimmel** [comment]
> Let's keep this issue open until we update the CSL information in USAGE.md.

Opened https://github.com/manubot/rootstock/pull/338. @thorowitz can you see whether the updates in that PR clarify how to set the citation style?
