### ISSUE TITLE
setting environment variables

### ISSUE THREAD

**Issue by thorowitz** [manubot/rootstock#335]
The instructions in the `build` directory state

> To build a DOCX file of the manuscript, set the BUILD_DOCX environment variable to true. For example, use the command BUILD_DOCX=true bash build/build.sh. To export DOCX for all CI builds, set an environment variable (see docs for GitHub Actions or Travis CI). 

It's not clear (to me) _where_ to set these environment variables. Do I edit `~/.github/workflows/manubot.yaml`? `~/build/environment.yml`?

**Comment by agitter** [comment]
If you are primarily using GitHub Actions to build and deploy the manuscript, then you would edit `.github/workflows/manubot.yaml`.  One way to set the environment variables would be to add a line here
https://github.com/manubot/rootstock/blob/073ce0e4e81c82e1ce8c55caeab0ebc6fd0f840c/.github/workflows/manubot.yaml#L14

Line 14 currently sets the `GITHUB_PULL_REQUEST_SHA` environment variable.  You could add a new line 15
```
      BUILD_DOCX: true
```
The spacing matters, so be sure that the new environment variable has the same number of preceding spaces as the one in line 14.

**Comment by thorowitz** [comment]
Thanks!
