### ISSUE TITLE
raw citation metadata

### ISSUE THREAD

**Issue by thorowitz** [manubot/rootstock#343]
The USAGE.md file says that

> For references that do not have any of the persistent identifiers above, use a raw citation like @raw:old-manuscript. Metadata for raw citations must be provided manually.

Where would this metadata go? From what I can glean from the Pandoc documentation, it would go in a .yaml file, but what this file should be called or where it should go in the Manubot project hierarchy is not clear.

**Comment by agitter** [comment]
There are some additional instructions about raw citations and manual references further down in USAGE.md: https://github.com/manubot/rootstock/blob/master/USAGE.md#reference-metadata

We could link those from the text you quoted above so it is more obvious where to specify the manual references.  The rootstock manuscript has an example of a [manual references json file](https://github.com/manubot/rootstock/blob/master/content/manual-references.json) and the demo manuscript has an example of a [manual references bib file](https://github.com/manubot/try-manubot/blob/master/content/manual-references.bib).

**Comment by thorowitz** [comment]
Ah, yes. A within-document link would be great. Thanks.

**Comment by dhimmel** [comment]
> Ah, yes. A within-document link would be great. Thanks.

Added in https://github.com/dhimmel/manubot-rootstock/commit/ad4c5a558f8b8fa3c901d22fb7d4d9f2fc978a8a, which is part of #342. Once this PR is merged, citations will become a lot more flexible. You'll no longer be required to prefix manual reference citation keys with `raw:`.
