### ISSUE TITLE
How will changing 'master' to 'main' affect manubot build?

### ISSUE THREAD

**Issue by jaybee84** [manubot/rootstock#349]
https://github.com/jaybee84/ml-in-rd/issues/62#issue-641308795

**Comment by agitter** [comment]
Cross-referencing #341, which has some discussion and links to the `ml-in-rd` repo that show how to change the branch from which manuscripts are deployed.  Similar steps would be taken to deploy from `main`.

In terms of reconfiguring this rootstock repository to use `main` instead of `master`, my thoughts are that we may want to wait until GitHub implements its change so that our workflows and instructions are consistent with theirs.  [Recent news](https://www.cnet.com/news/microsofts-github-is-removing-coding-terms-like-master-and-slave/) makes it sound like that change is coming soon but still in progress.

We would also need to provide additional instructions in `SETUP.md` for anyone merging upstream rootsock changes.

**Comment by jaybee84** [comment]
Thanks @agitter !

**Comment by dhimmel** [comment]
It looks like the `master` branch name is hardcoded in several places, especially in the CI scripts and SETUP. It won't be too hard to change this repo such that new manuscripts use a different default branch. Doing this in a way that is backwards compatible for existing manuscripts that already use `master` might be more challenging.

> my thoughts are that we may want to wait until GitHub implements its change so that our workflows and instructions are consistent with theirs.

I agree. At least until GitHub provides more clarity on what the default branch name will be in the future... do we know `main` is what it will be. Hopefully, GitHub announces their plans ASAP so we can have a timeline on when we can roll this change out.

**Comment by dhimmel** [comment]
More info on GitHub's updates at https://github.com/github/renaming.

Also recent blog post [GitHub Actions: Better support for alternative default branch names](https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/):

> We have updated all of our [starter workflows](https://github.com/actions/starter-workflows) to use a new `$default-branch` macro rather than the previously hardcoded `master`. You can take advantage of this feature in your [custom starter workflows as well](https://docs.github.com/en/actions/configuring-and-managing-workflows/sharing-workflow-templates-within-your-organization).

We should look into using `$default-branch` such that we begin removing hardcoded references to `master`. Ideally, we can support a default branch of any name. At that point, we might be able to switch rootstock to `main` with minimal disruption.

**Comment by dhimmel** [comment]
I just switched the default branch for `manubot/manubot` to `main` in https://github.com/dhimmel/manubot/commit/0c2e5b28809acd7c9ca76152146ddc24345d0781. But this is unrelated to the default branch used by rootstock.

**Comment by dhimmel** [comment]
Linking to https://github.com/pystatgen/sgkit-publication/commit/4f723fac8eea1bb4caea55f755efc5dc0d696fe0 by @eric-czech.

**Comment by dhimmel** [comment]
The default branch for Rootsock has been switched to main in https://github.com/manubot/rootstock/pull/399. From the updated [SETUP.md](https://github.com/manubot/rootstock/blob/690aac113b4ee7dbb32a0af10a3d36c51a207025/SETUP.md#default-branch):

> On 2020-10-01, GitHub [changed](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/) the default branch name for new repositories from `master` to `main`.
More information on GitHub's migration is available at [github/renaming](https://github.com/github/renaming).
> 
> On 2020-12-10, Manubot [updated](https://github.com/manubot/rootstock/pull/399) the Rootstock default branch to `main`.
> For existing manuscripts, the default branch will remain `master`,
> unless manually switched to `main`.
> Rootstock has been configured to run continuous integration on both `main` and `master`,
> so existing manuscripts can, but are not required, to switch their default branch to `main`.
> 
> Upgrading to the latest Rootstock will change several READMEs links to `main`.
> For manuscripts that do not plan to switch their default branch,
> do not include these changes in the upgrade merge commit.

I'm going to upgrade some existing manuscripts to check everything is working. But absent any issues, users should be able to migrate existing manuscripts (after upgrading to the latest rootstock).
