### ISSUE TITLE
justified text alignment

### ISSUE THREAD

**Issue by igordot** [manubot/rootstock#353]
I just started exploring manubot. I saw it was possible to do center and right-alignment. However, there does not seem to be an option to fully justify text where the text falls flush with both margins. This should be possible with at least HTML and Word output (it might be more complicated with PDF). Is it possible to add that feature?

**Comment by dhimmel** [comment]
I think this should be possible using the `text-align: justify` style in HTML. The PDF is created from HTML, so it should apply there. 

References:

- https://www.w3schools.com/cssref/pr_text_text-align.ASP
- https://stackoverflow.com/a/40438921
- https://www.w3schools.com/cssref/css3_pr_text-justify.asp

@vincerubinetti might be able to provide the best CSS to justify text for all manuscript paragraphs.

The DOCX probably won't be affected, but you could edit the DOCX document provided to  `--reference-doc`.

**Comment by igordot** [comment]
I thought I can only edit the markdown files. Aren't the HTML files automatically generated?

**Comment by vincerubinetti** [comment]
Add this to your `default.html` theme:

```css
p {
  text-align: justify;
}
#refs p {
  text-align: left;
}
```

The second rule overrides the first in the case of the paragraph elements in the bibliography section, where justifying the text doesn't look good.

Check to make sure this doesn't have any unintended side effects, but from my limited testing, it should be okay.

**Comment by dhimmel** [comment]
@igordot that file is located at [`build/themes/default.html`](https://github.com/manubot/rootstock/blob/ce827c7789163dca33dfa3bd2df7aa828e57485d/build/themes/default.html). It ends up being inserted into the HTML document Pandoc generates.

**Comment by vincerubinetti** [comment]
> I thought I can only edit the markdown files. Aren't the HTML files automatically generated?

Yes the HTML files are automatically generated. But you can customize the look/style of them by editing the CSS in the `/build/themes/default.html` theme file. This will affect all of your future generated manuscripts in that repo.

**Comment by igordot** [comment]
Thank you for clarifying. What would I need to edit for DOCX?

**Comment by vincerubinetti** [comment]
`ctrl+shift+alt+s` to open the styles pane. Find the `normal` style, and click the down arrow and find "modify...". Then change the alignment of the style to justify:
![image](https://user-images.githubusercontent.com/8326331/86392191-09c95980-bc69-11ea-9d0c-7700b53e61bf.png)

I think that should change the justification of all the text by default. If that has unintended side effects, try modifying the `body text` style instead of the `normal` style. I'm not a word expert though. Idk if they have a style just to apply to paragraphs (and not, for example, text in tables or captions).

**Comment by vincerubinetti** [comment]
Closing and deferring to #413
