### ISSUE TITLE
GitHub Actions not working?

### ISSUE THREAD

**Issue by ybukhman** [manubot/rootstock#357]
Hi,

I have set-up a new manuscript following instructions in https://github.com/manubot/rootstock/blob/master/SETUP.md#creating-a-new-manuscript. My manuscript is at https://github.com/ybukhman/blue_whale_genome_paper. I have chosen GitHub Actions for CI as the suggested default. However, the links to GitHub pages that are supposed to display the formatted manuscript are broken. Is there something I am missing?

The links are here:
* HTML manuscript at https://ybukhman.github.io/blue_whale_genome_paper/
* PDF manuscript at https://ybukhman.github.io/blue_whale_genome_paper/manuscript.pdf

**Comment by agitter** [comment]
I'll check into this more closely after my afternoon meetings @ybukhman.  In the meantime, could the problem be related to this https://github.com/manubot/rootstock/issues/331#issuecomment-615874570

**Comment by agitter** [comment]
Your GitHub Actions [build ](https://github.com/ybukhman/blue_whale_genome_paper/runs/899582124) ran successfully.  The manuscript was pushed to the [`gh-pages` branch](https://github.com/ybukhman/blue_whale_genome_paper/blob/gh-pages/manuscript.pdf) successfully.

I think the GitHub Pages settings solution I linked above (https://github.com/manubot/rootstock/issues/331#issuecomment-615874570) will fix the problem.  Please let us know if it does not.

**Comment by ybukhman** [comment]
Yes, this has worked. Many thanks!
