### ISSUE TITLE
Change caption style

### ISSUE THREAD

**Issue by mbhall88** [manubot/rootstock#364]
Hi,

Is it possible to change the style of figure captions? For example, I'd like to make the font smaller.

**Comment by agitter** [comment]
The figure caption styles are controlled via CSS in a (confusingly-named for Pandoc-related reasons) file [`build/themes/default.html`](https://github.com/manubot/rootstock/blob/master/build/themes/default.html).  I made a pull request in a demo manuscript https://github.com/agitter/my-manuscript/pull/17 showing how to modify this in line 194.  A few CSS options for the font size (em, pt, px) are shown in https://github.com/manubot/rootstock/issues/239#issuecomment-507288671

**Comment by mbhall88** [comment]
Perfect. Thank you!
