### ISSUE TITLE
Table of contents not clickable on phones and tablets 

### ISSUE THREAD

**Issue by nathanael-fijalkow** [manubot/rootstock#369]
I noticed the following unfortunate behaviour on tablets (a Galaxy tab) and mobile phones (tried on a few, including Android and IPhone): the table of contents can be toggled by clicking on the top left (so, JavaScript is activated). However it cannot be used: if I click on some document section (meaning, tap with my finger on the screen), the table of contents disappears instead of bringing me to the part of the document I clicked on.

**Comment by dhimmel** [comment]
Hmm interesting. Sounds like a different issue than https://github.com/manubot/rootstock/issues/306.

@nathanael-fijalkow do you have a public URL where this is happening? Does it happen at https://manubot.github.io/rootstock/v/15db6237effc6edb2b8e675ea5cb8a17188d1e2c/

> the table of contents disappears instead of bringing me to the part of the document I clicked on.

I am not sure what the intended behavior is:

1. bring you to section, close TOC
2. bring you to section, keep TOC expanded

@vincerubinetti do you know?

**Comment by vincerubinetti** [comment]
If I recall correctly, the intended behavior was, if you're on a small enough screen, clicking on a TOC entry will bring you to the section and close the table of contents, and clicking "off" of the TOC panel (on the body of the document) will also close the table of contents.

> click on some document section (meaning, tap with my finger on the screen), the table of contents disappears instead of bringing me to the part of the document I clicked on.

Can you please clarify this. Do you mean you're clicking on a TOC entry, or on a part of the document body itself. If you're doing the former, maybe the real issue is that it's not bringing you to the section you wanted. But either way, the TOC panel should close.

**Comment by nathanael-fijalkow** [comment]
@dhimmel yes, it happens for this example, but also for all others I have tried (random sample of the catalog).

@vincerubinetti indeed I click on a TOC entry, and the TOC closes but does not bring me anywhere. 

Actually it seems that the TOC is agnostic to clicks: if for instance below the place where I click on the TOC there is a link, such as a section head, then it is activated (the section is expanded / collapsed). And at the same time the TOC is closed. 

I made a short video but it seems that Github does not allow me to share it here. If it can help I'll put it up online and link it here.

**Comment by vincerubinetti** [comment]
Can you provide us a link to the Manuscript where this happens. Also, do you have the Hypothesis plugin enabled?

If you zip the video file, you should be able to attach it to this thread, unless the video file is too big maybe.

**Comment by nathanael-fijalkow** [comment]
@vincerubinetti yes that's a good idea here's the zip file. 
[SVID_20201003_202500_1.zip](https://github.com/manubot/rootstock/files/5322163/SVID_20201003_202500_1.zip)

Yes, Hypothesis is active (by default).

**Comment by vincerubinetti** [comment]
Okay I'm actually able to replicate this on my mobile devices as well. This must be a regression because I remember testing this plugin thoroughly on mobile devices.

@dhimmel I can get to this on Monday.

**Comment by dhimmel** [comment]
Thanks @nathanael-fijalkow for the report and helpful screen recording. Thanks @vincerubinetti for the fix and enhanced behavior.

Should be fixed at https://manubot.github.io/rootstock/v/37a11499b204458dfb620970f103769289b31e1f/
