### ISSUE TITLE
MathJax undefined with latest plugin

### ISSUE THREAD

**Issue by matthewturk** [manubot/rootstock#377]
Hi!  We recently updated to the current rootstock, and we're now getting "MathJax" undefined errors.  It seems that in #375 the math plugin was changed from loading:

`https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML`

to:

`https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-MML-AM_CHTML.js`

Is this an intentional change?  I can't *quite* tell but reading the [mathjax docs](https://docs.mathjax.org/en/v2.7-latest/config-files.html#the-tex-mml-am-chtml-configuration-file) it seems like maybe it either should be the old style where the config is specified, or the config could be manually added to the `MathJax.Hub.Config` call in `math.html` to specify `TeX-MML-AM_CHTML`.

Or, if indeed we're misconfigured somehow in our instance of manubot, any suggestions for how to fix it on our end would be very helpful.

**Comment by agitter** [comment]
Thanks for reporting this.  This was an intentional change.  However, we get the same error on the rootstock manuscript https://manubot.github.io/rootstock/#eq:regular-equation so I don't think you misconfigured anything.

Error message:
```
Uncaught ReferenceError: MathJax is not defined
    at TeX-MML-AM_CHTML.js:15
```

@vincerubinetti can you please investigate?

**Comment by vincerubinetti** [comment]
Made a PR. Can you let me know if this fixes it. I'm unable to test it on my machine right now.

**Comment by matthewturk** [comment]
Thank you!

**Comment by agitter** [comment]
Thanks @vincerubinetti!

@matthewturk this should be fixed now.  You may want to wait a couple minutes to confirm the equations at https://manubot.github.io/rootstock/#eq:regular-equation work before updating your manuscript again.
