### ISSUE TITLE
Internal references in document

### ISSUE THREAD

**Issue by habi** [manubot/rootstock#380]
I'd like to write "as described in the section 'cropping' above" in my manuscript, according to https://opensource.com/article/18/9/pandoc-research-paper

But this did not work in this commit https://github.com/habi/zmk-tooth-cohort-method-manuscript/commit/30ba4b376255ad6f4e449d07bcd0cfa5f6e591c6, the [generated files](https://github.com/habi/zmk-tooth-cohort-method-manuscript/suites/1406162000/artifacts/23425385) have `[???]` as an internal link.

Is this possible with `manubot`?

**Comment by dhimmel** [comment]
Currently you have:

```
#### Dataset cropping {#sec:cropping}

Cropping the datasets with a simple algorithm - as described in subsection 'Dataset cropping' [@sec:cropping] - greatly reduces the size of the datasets on disk.
```

Try changing the section link to `as described in subsection '[Dataset cropping](#sec:cropping)'`. In fact, I think pandoc will even be able to do the following:


```
#### Dataset cropping

Cropping the datasets with a simple algorithm - as described in subsection [Dataset cropping] - greatly reduces the size of the datasets on disk.
```

See https://pandoc.org/MANUAL.html#extension-auto_identifiers.

**Comment by dhimmel** [comment]
The reason `@sec:cropping` doesn't work is because `@` indicates a citation rather than just a link, and manubot does not know how to deal with a citation to `@sec:cropping`.

**Comment by agitter** [comment]
I'm doing some testing with [pandoc-secnos](https://github.com/tomduck/pandoc-secnos) as well to see if that supports numbered section references with `@`.

**Comment by habi** [comment]
> In fact, I think pandoc will even be able to do the following:

That's indeed the case, and maybe the simplest way: https://github.com/habi/zmk-tooth-cohort-method-manuscript/commit/99dfce3032d524d3044e8e2e0366ea5210445aad

**Comment by agitter** [comment]
@habi we typically use Markdown links as @dhimmel showed above.  However, it is possible to have LaTeX-style numbered section references with pandoc-secnos.  I made a pull request in a demo manuscript showing what you need to change to enable pandoc-secnos:
- Install the package by adding it to `build/environment.yml`
- Run the pandoc filter in `build/pandoc-defaults/common.yaml`
- Use either style section identifier, either the default identifier or an explicit one will work.  Both are shown in my example `content/02.main-body.md`.

The default section numbering is unintuitive.  You can tweak that using Pandoc settings, especially `shift-heading-level-by`.  An example is https://github.com/greenelab/covid19-review/blob/fce6c96d9ddb149f5362decdbcf96ba5de17d5c6/build/pandoc/defaults/common.yaml#L17-L20

**Comment by habi** [comment]
> However, it is possible to have LaTeX-style numbered section references with pandoc-secnos.

Thanks for investigating and giving an example.
At the moment we don't need numbered references, maybe at final submission, but then it most probably will be needed to be a LaTeX file anyways.
