### ISSUE TITLE
Error running filter pandoc-manubot-cite

### ISSUE THREAD

**Issue by thorowitz** [manubot/rootstock#390]
I just made a minor tweak to a manuscript file, and now I get an "all checks have failed" error when I try to merge the pull request. If I read this correctly, it seems to be a failure in the pandoc-manubot-cite process, but I am mystified because I have not changed any citations. I have copied the relevant part of the job error message below:

```python-traceback
[INFO] Running filter pandoc-manubot-cite 
Traceback (most recent call last): 
File "/usr/share/miniconda3/envs/manubot/bin/pandoc-manubot-cite", line 8, in <module> 
sys.exit(main()) 
File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/manubot/pandoc/cite_filter.py", line 222, in main 
doc = pf.load(input_stream=args.input) 
File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/io.py", line 58, in load 
doc = json.load(input_stream, object_hook=from_json) 
File "/usr/share/miniconda3/envs/manubot/lib/python3.7/json/__init__.py", line 296, in load 
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) 
File "/usr/share/miniconda3/envs/manubot/lib/python3.7/json/__init__.py", line 361, in loads 
return cls(**kw).decode(s) 
File "/usr/share/miniconda3/envs/manubot/lib/python3.7/json/decoder.py", line 337, in decode 
obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
File "/usr/share/miniconda3/envs/manubot/lib/python3.7/json/decoder.py", line 353, in raw_decode 
obj, end = self.scan_once(s, idx) 
File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/elements.py", line 1371, in from_json 
return _res_func[tag](c) 
File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/table_elements.py", line 391, in table_from_json 
caption = Caption(*c[1][1], short_caption=c[1][0]) 
IndexError: list index out of range 
Error running filter pandoc-manubot-cite: 
Filter returned error status 1 
Error: Process completed with exit code 83.
```

**Comment by agitter** [comment]
This isn't an error you caused, it has to do with the Manubot build environment changing in an unexpected way.  The two solutions in https://github.com/manubot/rootstock/issues/387#issuecomment-724673668 will fix this.  If you want to upgrade rootstock to the latest version and get stuck, we can help with a pull request.

**Comment by thorowitz** [comment]
Thanks! Implemented solution #1, and that worked.

**Comment by thorowitz** [comment]
I'm trying to update the rootstock, and have run into difficulties. My pull request failed checks at "set environment variables" with the following errors:
`Error: Unable to process command '::set-env name=TRIGGERING_SHA_7::cd0f78e' successfully.`

`Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/`

**Comment by agitter** [comment]
This is caused by the an old version of the "Set Environment Variables" step and the `setup-miniconda` action in the GitHub Actions workflow.  Is your `.github/workflows/manubot.yaml` file in sync with the manubot/rootstock version?

Did you execute the `git pull --no-ff --no-rebase --no-commit rootstock master` step to get the latest version of rootstock before updating your manuscript?

**Comment by thorowitz** [comment]
manubot.yml is bot yet in sync. That's part of the whole package of changes I'm trying to push.

I did execute `git pull --no-ff --no-rebase --no-commit rootstock master`

**Comment by agitter** [comment]
Perhaps something happened in a recent or prior merge such that parts of `manubot.yaml` are not being updated in your pull request.  The easiest solution might be to manually copy these parts of `manubot.yaml` from rootstock into your version:
https://github.com/manubot/rootstock/blob/97b294802ffcd39071b6e5b8ab59f60faf4be118/.github/workflows/manubot.yaml#L17-L21
and
https://github.com/manubot/rootstock/blob/97b294802ffcd39071b6e5b8ab59f60faf4be118/.github/workflows/manubot.yaml#L35

If you want help with this, I could make a pull request in your repository.

**Comment by thorowitz** [comment]
Yes, that would be great if you could create a pull request!

t

**Comment by thorowitz** [comment]
Thanks for creating the pull request. I successfully merged it. However, I'm still getting the `Unable to process command '::set-env name=TRIGGERING_SHA_7::a79967e' successfully.` error.

**Comment by agitter** [comment]
The problem is that the pull request was not merged into your `master` branch.  You'll need to reopen `#167` and then merge that to `master`.  It was closed, not merged.

**Comment by thorowitz** [comment]
I'm not entirely sure what happened there, but it seems to be working again. Thanks!

**Comment by agitter** [comment]
After you reopened pull request 167 in your repository, I merged it to master.  That applied the rootstock updates to your main builds.  You should be all set now.
