### ISSUE TITLE
No docx output file found

### ISSUE THREAD

**Issue by jaybee84** [manubot/rootstock#414]
In our manuscript repo, the [yaml file](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/.github/workflows/manubot.yaml) has been updated to build a manuscript.docx  output.
But no docx file is generated or found in the `output` dir.

**Comment by agitter** [comment]
This looks like it is working now.  I see `manuscript.docx` in https://github.com/jaybee84/ml-in-rd/tree/output

**Comment by jaybee84** [comment]
Thanks @agitter! 
I think I was looking at the wrong place (`output dir` instead of `output branch`). I see them now on the appropriate branch. Really appreciate the prompt follow up :)
