### ISSUE TITLE
Changing CSL

### ISSUE THREAD

**Issue by VerenaPuehringer** [manubot/rootstock#424]
Hi, 
I would like to switch the CSL style to Journal of Animal Ecology. I tried to integrate this change in build.sh with the following command: 

CSL_PATH=https://github.com/citation-style-language/styles/raw/0f332db9384bfbe5f9028d82b2fb4b9570c1325b/dependent/journal-of-animal-ecology.csl  
BIBLIOGRAPHY_PATH=output/references.json
INPUT_PATH=output/manuscript.md

However, I get back this error message when building the manuscript:
Could not find bibliography file: output/references.json

Thus, I am not sure how to link the bibliography path and input path to the output branch? 

I have another question regarding the conversion to a .docx file. Because even though the command in the build.sh is set to true for the conversion to .docx, the .docx file is not built in the output branch. Do I have to change something else in the build.sh file in order to create a .docx file?

The repository is set to private at the moment. But if you need to access it I can change the settings to public.

Could you please help me with these problems?

Thanks in advance!

Cheers,
Verena

**Comment by dhimmel** [comment]
> I would like to switch the CSL style to Journal of Animal Ecology. I tried to integrate this change in build.sh with the following command:

If you're using the most recent version of Manubot, try changing the following instead (to set the CSL to the Journal of Animal Ecology):

https://github.com/manubot/rootstock/blob/99776841cd694c1c612060114ecc0f3e5f686e5f/build/pandoc/defaults/common.yaml#L11-L12

Do you know whether you're using a recent version of Manubot? Can you see what the most recent rootstock commit is?

> I have another question regarding the conversion to a .docx file. Because even though the command in the build.sh is set to true for the conversion to .docx, the .docx file is not built in the output branch. Do I have to change something else in the build.sh file in order to create a .docx file?

You have added a line like `BUILD_DOCX=true` in build.sh? That should work. Another option is to add the following to the GitHub action step or job:

```yaml
    env:
      BUILD_DOCX: true
```

You can also enable for a single local build like `BUILD_DOCX=true bash build/build.sh`.

> The repository is set to private at the moment. But if you need to access it I can change the settings to public.

If my suggestions here don't help figure out the problems, then the easiest way is for us to look directly at the manuscript.

**Comment by VerenaPS** [comment]
Hi,
thank you very much! Your suggestions worked.
Cheers!
