### ISSUE TITLE
There isn't a GitHub Pages site here

### ISSUE THREAD

**Issue by aseedb** [manubot/rootstock#430]
I have started a new manuscript [at this repository](https://github.com/aseedb/synaptic_tomo_ms) following the procedure given in the introduction video. The manuscript gets built and I get an index.html and a manuscript.pdf in the root of the gh-pages branch. Nevertheless, the Github Pages links https://aseedb.github.io/synaptic_tomo_ms/ and https://aseedb.github.io/synaptic_tomo_ms/manuscript.pdf do not work; I am getting a 404 error. 
I am quite inexperienced with github pages and would appreciate any pointer to the possible cause of this error.

**Comment by dhimmel** [comment]
From https://github.com/manubot/rootstock/blob/main/SETUP.md#github-actions

> GitHub Actions is usually able to deploy without any additional setup using the GITHUB_TOKEN for authentication. GitHub Pages deployment using GITHUB_TOKEN recently started working on GitHub without an official announcement. If it does not work for you after completing this setup, try reselecting "gh-pages branch" as the Source for GitHub Pages in the repository Settings. GitHub Pages should now trigger on the next commit. If not, let us know. For more reliable deployment on GitHub, you can also use an SSH Deploy Key instead (see below).

My guess is that you need to reselect gh-pages under settings. Then hopefully it works (you might have to rerun the CI build).

**Comment by aseedb** [comment]
Thank you @dhimmel ! Source was set to None. After setting it to gh-pages it worked like a charm, without the need to rerun the CI build. 👍
