### ISSUE TITLE
Conditionally disable the docker builds

### ISSUE THREAD

**Issue by multimeric** [manubot/rootstock#440]
I'm on a machine with Docker installed, so `build/build.sh` will use it to build the manuscript. However, this is quite slow for me, and I prefer the WeazyPrint method 100% of the time when I'm drafting. For this reason I would appreciate a way to turn off the docker builds by _choice_. I know that the build shell script is part of the repo and therefore editable, so I have done this:

```patch
diff --git a/build/build.sh b/build/build.sh
index 778c958..5b4c39b 100755
--- a/build/build.sh
+++ b/build/build.sh
@@ -49,3 +49,3 @@ DOCKER_RUNNING="$(docker info &> /dev/null && echo "yes" || true)"
 # If Docker is not available, use WeasyPrint to create PDF
-if [ "${BUILD_PDF,,}" != "false" ] && [ -z "$DOCKER_RUNNING" ]; then
+if [[ "${BUILD_PDF,,}" != "false" && (-z "$DOCKER_RUNNING" || -n "$SKIP_DOCKER") ]]; then
   echo >&2 "Exporting PDF manuscript using WeasyPrint"
@@ -62,3 +62,3 @@ fi
 # If Docker is available, use athenapdf to create PDF
-if [ "${BUILD_PDF,,}" != "false" ] && [ -n "$DOCKER_RUNNING" ]; then
+if [[ "${BUILD_PDF,,}" != "false" && -n "$DOCKER_RUNNING" && -z "$SKIP_DOCKER" ]]; then
   echo >&2 "Exporting PDF manuscript using Docker + Athena"
```
(in hindsight it would probably have been neater to just add this logic to `DOCKER_RUNNING`)

I'm wondering if there's an interest in pushing this feature upstream.

**Comment by dhimmel** [comment]
For option names, I don't have a strong preference between `SKIP_DOCKER`, `USE_DOCKER`, `MANUBOT_SKIP_DOCKER` and `MANUBOT_USE_DOCKER`. We did want to start using a manubot prefix `MANUBOT_` for manubot related options, but this is also a bit inconsistent at this point.

**Comment by dhimmel** [comment]
@multimeric if you have time, would love your feedback on https://github.com/manubot/rootstock/pull/449?
