### ISSUE TITLE
Travis CI builds disabled due to negative credit balance

### ISSUE THREAD

**Issue by ben-heil** [manubot/rootstock#446]
The Travis-CI build badge in the README reports an error, possibly due to the travis-ci.org -> .com switch. It looks like the `.travis.yml` file is only included for legacy reasons, so should the README badge be removed?

**Comment by agitter** [comment]
> it's a lot of support effort and now requires payment without any unique benefit

Exactly.  I don't see any reason to use it for a new manuscript.  I'm okay removing Travis support entirely.  We would need to update `SETUP.md` in several places to note it is no longer supported and remove the setup instructions.

Existing projects using Travis CI could be affected if we delete `.travis.yml` and they update rootstock without looking at the merge carefully.  We could help users restore that file if they get stuck.  I can't think of a better way to avoid removing the file if it is in use.

**Comment by dhimmel** [comment]
> Existing projects using Travis CI could be affected if we delete `.travis.yml` and they update rootstock without looking at the merge carefully. We could help users restore that file if they get stuck

Yeah! Happy to help legacy users upgrade to GitHub Actions. I imagine there are not too many active manuscripts still using Travis, especially now that it's a paid service.
