### ISSUE TITLE
Possibility to have a classical Table Of Content to pdf/word outputs

### ISSUE THREAD

**Issue by Adafede** [manubot/rootstock#457]
Hi,

Tried looking for a way to have a "classical TOC" at the beginning in word/pdf outputs but could not find it.

Would be a nice option I guess?

Thank you so much again for your beautiful tool! 👍🏼

**Comment by dhimmel** [comment]
Pandoc [has](https://pandoc.org/MANUAL.html) a `--table-of-contents` option. Not sure exactly how or where it will insert the TOC, but worth a try.

**Comment by Adafede** [comment]
Indeed, seems to work for word/latex but AthenaPDF does not seem to have an equivalent.

So I tried generating the HTML with `--toc`, and then the PDF is with a TOC "as expected", but it forces the HTML to have it integrated into the main text along with the sidebar (it is inserted right after the title, before anything else)

In html/pdf output, it comes without `Table of content` header, not the prettiest but well...
In docx output, a `Table of content` header is printed before.
 
Thanks already!
