### ISSUE TITLE
Changing bibliography style

### ISSUE THREAD

**Issue by ch728** [manubot/rootstock#464]
Is there a way to change the default bibliography style?

**Comment by dhimmel** [comment]
Yes, see [this section](https://github.com/manubot/rootstock/blob/9a22fab4497f80f501ea361d028f26888ad9d5a0/USAGE.md#custom-formatting) of USAGE:

**Comment by ch728** [comment]
Ah, not sure how I missed that section! I swapped out the .csl  and now I'm in business. Thanks!
