### ISSUE TITLE
[feature request] Abbreviations in the same way as references

### ISSUE THREAD

**Issue by Adafede** [manubot/rootstock#468]
Hi manubot team!

I thought that having a mechanism to be able to link an abbreviation to its definition into an abbreviation list such as it is currently done for references would be awesome! (with the links allowing to switch easily from one to another in the HTML)

Don't know how feasible that is but wanted to share the idea!

Best,

**Comment by dhimmel** [comment]
Pandoc `definition_lists` look like they might work ([extension](https://pandoc.org/MANUAL.html#extension-definition_lists) enabled by default).

Source markdown and pandoc command:

```bash
echo "
I am writing something nice with an abbreviation for [ABBREV2](#abbrev-2):

## Abbreviations

ABBREV1
  ~ Definition 1

[ABBREV2]{#abbrev-2}
  ~ Definition 2a
  ~ Definition 2b
" | pandoc --to=html
```

Output HTML:

```html
<p>I am writing something nice with an abbreviation for <a
href="#abbrev-2">ABBREV2</a>:</p>
<h2 id="abbreviations">Abbreviations</h2>
<dl>
<dt>ABBREV1</dt>
<dd>
Definition 1
</dd>
<dt><span id="abbrev-2">ABBREV2</span></dt>
<dd>
Definition 2a
</dd>
<dd>
Definition 2b
</dd>
</dl>
```

Which will render to something like (possibly with different indentation, we could always touch up the styles):

![image](https://user-images.githubusercontent.com/1117703/171616813-35e5cfef-0709-465c-b2ca-6a60664a4e63.png)

There's also a plugin https://kprussing.github.io/pandoc-acro/ ([github](https://github.com/kprussing/pandoc-acro)), but might be easiest to try the builtin solution first.

**Comment by dhimmel** [comment]
> a mechanism to be able to link an abbreviation to its definition into an abbreviation list such as it is currently done for references would be awesome! (with the links allowing to switch easily from one to another in the HTML)

Sounds like you're also interested in being able to look at an abbreviation in the abbreviation list and cycle through all instances of it. That would be nice but probably not as essential as find-in-page usually does a good job with abbreviations, as they often can be distinct from other text.

**Comment by Adafede** [comment]
The first part essentially already does the job, as you say, thank you very much!

**Comment by dhimmel** [comment]
Cool, should we close the issue or anything else that we should do?

**Comment by dhimmel** [comment]
> Depending on how the non-essential nice addition has an interest

Can you elaborate on what possible enhancements would be? There are a couple suggestions in your initial comment, but let's be more specific in the context of the current `definition_lists` solution and what else we could do.

**Comment by Adafede** [comment]
I imagined some hack to have the same ^ arrows as for the references to come back to the text and navigate occurrences as you mentioned. But it is really anecdotical, the `definition_lists` are already 99.5% OK.

**Comment by dhimmel** [comment]
Got it. I agree that'd be cool. Probably need more adoption of `definition_lists` on individual manuscripts first and then we could think about adding a javascript plugin for the interactivity. Will close for now, but feel free to continue discussion.
