### ISSUE TITLE
Review Commons / Template Compatibility

### ISSUE THREAD

**Issue by cgreene** [manubot/rootstock#469]
I submitted my first manuscript to review commons using the standard manubot template. It came back with this comment:

> Corresponding author needs to be clearly indicated in the manuscript.
> Corresponding author marked in the manuscript needs to match the corresponding author marked on the submission page.

We might want to add a suggested corresponding author field + indicate in the template.

**Comment by dhimmel** [comment]
Past discussions on denoting corresponding authorship:

- https://github.com/manubot/rootstock/issues/312
- https://github.com/manubot/rootstock/issues/129

Pulling out the comment on various formats manuscripts have used:

- https://greenelab.github.io/meta-review/v/aa78ba9cbb2d874789cbfc9462dfb9aad19f655f/
- https://greenelab.github.io/meta-review/v/22b94633509d9d9c8cf3cca92d4e41d784da1bff/
- https://greenelab.github.io/deep-review/v/1c6b9c49439d2985e249e00fd09977bbb83b20af/
- https://lelaboratoire.github.io/rethink-prs-ms/v/9eeea5b70fa3bf20c3f11778bd72c79034163674/

I'm +1 to a standard YAML field to denote corresponding authors and a front-matter template displays corresponding authors if set.
