### ISSUE TITLE
no output saved in a forked manuscript

### ISSUE THREAD

**Issue by aseedb** [manubot/rootstock#473]
Hi, I have forked the manuscript of a colleague to work on it locally. Basically I just forked it and took no other setup steps. I then ran the github action to build the manuscript. The action runs without error and I can download the artifact zip file containing the pdf and other files. However, the output pdf is not to be found anywhere in the forked repo. All I can see is older versions of the pdf that were produced before the fork. Is it possible to setup the forked repo in order to get the pdf to appear in the repo?

**Comment by agitter** [comment]
Can you confirm that the "Deploy Manuscript" step of the GitHub Actions workflow ran?  If it did, then I would next check the GitHub Pages setup.  Perhaps that doesn't work automatically when forking a repo.

Following this [setup step](https://github.com/manubot/rootstock/blob/main/SETUP.md#github-actions)
> try reselecting "gh-pages branch" as the Source for GitHub Pages in the repository Settings. GitHub Pages should now trigger on the next commit.

**Comment by aseedb** [comment]
It did not execute the deploy (see picture) 
<img width="244" alt="image" src="https://user-images.githubusercontent.com/31647043/187620134-2b4d2ca9-2f44-4fcb-936d-2fb544927045.png">
I forgot to say that the repo is private.  Could this be the reason? If not then i try the full setup

**Comment by dhimmel** [comment]
Skipping deployment in forks is intentional, since often forks don't want a distinct HTML page. You can change this setting at


https://github.com/manubot/rootstock/blob/9504aa7751e9d5ca0e7df896bf3aeeb73d2fb262/.github/workflows/manubot.yaml#L94-L95


Remove `!github.event.repository.fork`

**Comment by aseedb** [comment]
Thank you guys for your support. @dhimmel your solution solved my problem.
