### ISSUE TITLE
Editing Demo Manuboat

### ISSUE THREAD

**Issue by kapilrs2** [manubot/rootstock#474]
How can I edit the standard manuboat table which contains information like Basic formatting, document organization and etc.

**Comment by agitter** [comment]
For table formatting, see the [table section](https://github.com/manubot/rootstock/blob/main/USAGE.md#tables) of the usage guide and the links within. If you are new to Manubot and markdown tables, you can also test changes in the demo manuscript https://github.com/manubot/try-manubot/. We will accept pull requests there so you can see how they affect the HTML output.
