### ISSUE TITLE
deployment timeout

### ISSUE THREAD

**Issue by aseedb** [manubot/rootstock#479]
All my deployment trials to github pages in [this repo ](https://github.com/aseedb/synaptic_tomo_ms) fail with timeout. Clearly this is because the artifact to upload has become gigantic. I suspect it is because of the versioning. Is it safe to delete some old version under [https://github.com/aseedb/synaptic_tomo_ms/tree/gh-pages/v](https://github.com/aseedb/synaptic_tomo_ms/tree/gh-pages/v)?  
Will it reduce the size of the artifact?

**Comment by dhimmel** [comment]
Hey @aseedb, another manuscript hit this issue at https://github.com/greenelab/covid19-review/issues/1177.

Yes, you should be able to selectively delete content in `gh-pages` to fix this. Let me take a quick look at your repo and see if I see an easy solution.

**Comment by dhimmel** [comment]
My suggestion would be to delete files in the images directory under versions, i.e. `v/*/images` on gh-pages.

Then for the future, consider putting images in a directory other content/images, such that they won't get copied into each new webpage output and embed them by GitHub URL instead.

**Comment by agitter** [comment]
@aseedb one thing I did when cleaning up https://github.com/greenelab/covid19-review/issues/1177 that may get lost in all the notes was make a backup before I started deleting old versions.  That way I could recover any old versions that turn out to be important later.  Even with a huge artifact, GitHub was okay making a release of the `gh-pages` branch in my case that zips all the content.  We also set up Zenodo archiving for releases, but the GitHub release may suffice.

**Comment by aseedb** [comment]
@dhimmel and @agitter thanks a lot for your quick answers! will try out

**Comment by dhimmel** [comment]
Another option would be to create a `gh-pages-backup-2022-11-17` branch instead of the release.

But also the gh-pages history still exists in completion right, so not sure anything is actually necessary for preservation.

**Comment by aseedb** [comment]
I have backed it up and severely deleted the gh-pages v's, and moved all the files that are not linked in the manuscript out of the /images directory in the main branch. Now deployment takes about 1 minute. Thanks.
