### ISSUE TITLE
AI workflow cannot create PR

### ISSUE THREAD

**Issue by SilasK** [manubot/rootstock#492]
I encountered problems in the ai revision workflow, not in the ai revision but in the pull request afterward. 

- I gave actions rights to create PRs. But it seems we need to give write access to actions.  
 I suggest clarifying this in the documentation. 
- For me, draft PRs were not allowed.

I don't know why this happened, maybe because I had a private repo?

**Comment by agitter** [comment]
Thanks for the suggestion. If these permissions aren't always enabled, I agree we should document them.

To confirm, is this the setting you needed to change?
Actions:
![image](https://user-images.githubusercontent.com/3532898/231927360-316fbe1b-3c78-4b85-9b03-f518f08d1278.png)

Was there a separate setting you needed to change to enable draft pull requests? [These docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) suggest they may be tied to the write permissions.

**Comment by SilasK** [comment]
Yes, I needed to change this settings.

I set draft to true in the workflow.yaml

Because I could not figure out how to allow draft PRs.

**Comment by dhimmel** [comment]
We should be able to set the permissions explicitly in `ai-revision.yaml`, such that default workflow permissions are overridden. We do this for `manubot.yaml`:

https://github.com/manubot/rootstock/blob/f3e0520060162f71f0950ea88d44de526d241ad1/.github/workflows/manubot.yaml#L41-L42
