### ISSUE TITLE
Error: The process '/usr/share/miniconda3/condabin/conda' failed with exit code 1

### ISSUE THREAD

**Issue by habi** [manubot/rootstock#499]
The GitHub actions on [one of my `manubot` manuscripts](https://github.com/habi/EAWAG-manuscript/actions) fails with the error message in the subject.

Can anyone suggest how I can fix this, as I was *just* getting ready to submit a revised version of it...

**Comment by dhimmel** [comment]
I think the actual error is [here](https://github.com/habi/EAWAG-manuscript/actions/runs/5623116620/job/15237125618#step:6:2688):

```
WARNING: Discarding https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz#sha256=607774cbba28732bfa802b54baa7484215f530991055bb562efbed5b2f20a45e (from https://pypi.org/simple/pyyaml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*). Command errored out with exit status 1: /usr/share/miniconda3/envs/manubot/bin/python /usr/share/miniconda3/envs/manubot/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpm_khiixs Check the logs for full command output.
  ERROR: Could not find a version that satisfies the requirement pyyaml==5.4.1 (from versions: 3.10, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1, 5.1.1, 5.1.2, 5.2b1, 5.2, 5.3b1, 5.3, 5.3.1, 5.4b1, 5.4b2, 5.4, 5.4.1, 6.0b1, 6.0, 6.0.1)
  ERROR: No matching distribution found for pyyaml==5.4.1
```

Will follow up with solutions

**Comment by dhimmel** [comment]
I am hoping that if you upgrade your rootstock as [described here](https://github.com/manubot/rootstock/blob/main/SETUP.md#merging-upstream-rootstock-changes), that should fix this issue. You will get an update to your [`environment.yml`](https://github.com/habi/EAWAG-manuscript/blob/d2a528e02378abd0b01fe95d1710cb53d8cd81ca/build/environment.yml) that hopefully will resolve this error.

The only challenging part is if there are any conflicts in the merge, but just resolve them such that the resolved version is how you want the new manuscript to be.

**Comment by habi** [comment]
Thanks a lot for the suggestion!
https://github.com/habi/EAWAG-manuscript/pull/15 seems to have fixed it, at least the action is not failing at `conda` after 2 or 3 minutes, but has been chugging along for more than 25 minutes now :)

The merge was a bit tricky because I've added the mastodon icon myself since starting the manuscript, but nothing too complicated for `git merge`.

**Comment by habi** [comment]
The 'turnaround' time has been quite long for a while, but is of very secondary concern, I'm happy if the process goes through without errors.
