### ISSUE TITLE
docx fails to open

### ISSUE THREAD

**Issue by slowkow** [manubot/rootstock#507]
I am trying to follow the tutorial, step by step, before editing any files to include my own text.

It seems like the PDF and HTML build OK. But the DOCX is not working.

When I run:

```
bash build/build.sh
```

It runs, and I get output files:

```
README.md
citations.tsv
manuscript.docx
manuscript.html
manuscript.md
manuscript.pdf
references.json
variables.json
```

I can open the HTML and PDF files, and they look mostly OK.

The HTML seems to be missing the ORCID logo:

![Screenshot 2023-11-30 at 12 33 06 PM](https://github.com/manubot/rootstock/assets/209714/150d6c11-cd66-4099-9007-fbac5799250c)

The PDF seems OK:

![Screenshot 2023-11-30 at 12 33 28 PM](https://github.com/manubot/rootstock/assets/209714/179a1496-8602-4d07-ae85-5e55d65264e8)

But the DOCX file does not open:

![Screenshot 2023-11-30 at 12 32 28 PM](https://github.com/manubot/rootstock/assets/209714/55380655-06c1-4fea-9b47-97bf5e3b9f3f)

**Comment by slowkow** [comment]
```
pandoc -v
pandoc 3.1.4
Features: +server +lua
Scripting engine: Lua 5.4
```

The following command produces a file that I can open with Word, but the equations are not rendered:

```
pandoc output/manuscript.html -o output/test.docx
```

![Screenshot 2023-11-30 at 12 42 19 PM](https://github.com/manubot/rootstock/assets/209714/4517b4b0-1d31-457c-93e6-859b86e20e3f)

**Comment by agitter** [comment]
> I can't open the docx files produced by manubot.

Is that still true if you remove equation numbering before exporting to docx? That is what I believe is causing the issue.
