### ISSUE TITLE
AppVeyor CI builds fail due to spellcheck dependencies

### ISSUE THREAD

**Issue by agitter** [manubot/rootstock#508]
The Appveyor build in https://github.com/greenelab/covid19-review/pull/1214 failed with the error
```
E: The repository 'http://apt.postgresql.org/pub/repos/apt bionic-pgdg Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'contrib/binary-i386/Packages' as repository 'http://download.virtualbox.org/virtualbox/debian bionic InRelease' doesn't support architecture 'i386'
```

I believe that is related to https://www.postgresql.org/message-id/ZN4OigxPJA236qlg%40msg.df7cb.de

**Comment by dhimmel** [comment]
Possibly we could update the appveyor [image](https://www.appveyor.com/docs/linux-images-software/) to `Ubuntu2204` at:

https://github.com/manubot/rootstock/blob/078af3a959b07118dc2f282357644ed96646ecab/.appveyor.yml#L23

Or we could consider getting rid of appveyor entirely and possibly adding PR comments to the GitHub action via something like:

- https://github.com/mshick/add-pr-comment
- https://github.com/thollander/actions-comment-pull-request

**Comment by dhimmel** [comment]
Fixed by https://github.com/manubot/rootstock/pull/509

Not against removing AppVeyor completely if we can replace with GH actions, but will close since the error is fixed.

**Comment by agitter** [comment]
Thanks for fixing this. I'm glad it wasn't too complicated.

I agree we could drop AppVeyor if either of us or a different contributor has time to look into those GitHub Actions alternatives in the future.
