### ISSUE TITLE
Deprecation Warnings / Recent Run

### ISSUE THREAD

**Issue by cgreene** [manubot/rootstock#515]
FYI there are some deprecation warnings on a recent run. 
<img width="888" alt="Screenshot 2024-07-31 at 7 28 12 AM" src="https://github.com/user-attachments/assets/ac763b31-4bbe-4510-9bd6-4d1107ceaff8">

The artifacts action one may hit us at some point.

**Comment by dhimmel** [comment]
Ah okay, let me look into upgrading these action dependencies

**Comment by dhimmel** [comment]
No more warnings in https://github.com/manubot/rootstock/actions/runs/10185651162!
