### ISSUE TITLE
manuscript fails to build with "Warning: Future Miniforge releases will NOT build Mambaforge installers." error

### ISSUE THREAD

**Issue by habi** [manubot/rootstock#519]
A build of one of my [manuscripts](https://github.com/microct-ana-unibe-ch/microvasculature-manuscript) was hit by a 'brown-out' day specified in the ["Sunsetting Mambaforge" blog post](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/) today.

I guess this is due to https://github.com/manubot/rootstock/blob/957ff8ebf04f1051aedb3fd17677e19ff2286b7a/.github/workflows/manubot.yaml#L82, but currently have no idea on how to fix it.

**Comment by habi** [comment]
Removing all 'traces' of `mamba` from the workflow file took care of that error: https://github.com/microct-ana-unibe-ch/microvasculature-manuscript/commit/be7e13bbfb2a06c641670ebe5de5c4c746deea63

**Comment by dhimmel** [comment]
Reopening this issue as a reminder to update the docs at

https://github.com/manubot/rootstock/blob/e5b62395d10a2b475c914726aafb510e41ce9015/build/README.md#L35
