### ISSUE TITLE
Creating a Manubot CSL that perfects the format of bibliographic entries

### ISSUE THREAD

**Issue by dhimmel** [manubot/rootstock#53]
Currently, Manubot uses [`style.csl`](https://github.com/greenelab/manubot-rootstock/blob/0a044058f3792927ae75da83396c6522a3990503/build/assets/style.csl) a slightly [modified](https://github.com/greenelab/deep-review/commit/6de72059eae196303cba12f99c5703703e12a1b8) version of `proceedings-of-the-royal-society-b.csl`. While this style is decent, I have some ideas for an optimal style. And of course, authors can always switch the style to that of whatever journal they'd like.

The style I envision uses numbers for citations, i.e. renders like`blah blah [1-5,7].`. Non bracketed citations could show author name like: `Pippi, Hippi, et al [7] wrote`.

Bibliographic entries would look something like:

1. [**Sci-Hub provides access to nearly all scholarly literature**](https://doi.org/10.7287/peerj.preprints.3100v1)
<sub><sup>Daniel S Himmelstein​, Ariel R Romero, Stephen R McLaughlin, Bastian Greshake Tzovaras, Casey S Greene</sup></sub>
_PeerJ Preprints_ (2017-07-20) <sub><sup>DOI: `10.7287/peerj.preprints.3100v1`</sup></sub>

Ideally, author names would be in smaller text and hyperlink to ORCID records when available. The smallness of text here is an exaggeration (limited formatting options).

Compared to historical bibliographic formats, the following points are stressed:

1. Unique identification is the most important aspect of a reference. A hyperlink or DOI is the single most important piece of information.
2. The title is the most salient human-readable piece of information
3. Just having a year for the date is too imprecise. The month and day are important for placing works in the proper historical context.
4. Authorship information is important, but often takes up too much of a reference. Having authorship information in smaller or lighter text would be nice.
5. Unless a reference is only available in a physical format, the volume / issue / page information is irrelevant.
6. Historical reference styles adopt vastly different styles based on the type of record (article, interview, etcetera). This is largely unnecessary. If anything, a badge can display the type of record.

There's a [webapp](http://editor.citationstyles.org/about/) to generate a custom CSL style. I've found it a bit difficult to use, but its probably the way to go.

One question is whether to print out the URL rather than hyperlink the title. The benefit of showing the URL would be for readers who have printed the PDF. However, if a reader is at a computer, they could always go back to the digital version with the hyperlink.

Suggestions welcome.

**Comment by agitter** [comment]
I like the idea of a custom CSL style.  We should emphasize what we think is important and not be beholden to tradition.

I generally agree with your points above.  Alternative viewpoints on the following:
> Just having a year for the date is too imprecise.

True, but we can't always reliably get more precise information.  Metadata for some older manuscripts includes placeholder days and months in some cases (e.g. January 1 of the year).  For some URLs, I doubt our ability to automatically retrieve accurate date stamps.

> Authorship information is important, but often takes up too much of a reference.

This may be reader-dependent.  I personally remember more past literature based on authors and dates than titles.  `Author X 2011` may mean something to me even though `This is the title of my important paper` does not.

I don't see a need to print the URL.  As a reader, I find it easier to search for the title than to type in a URL in most cases.

**Comment by agitter** [comment]
I noticed in the meta review manuscript that some of the reference whitespace was missing when CSL fields were absent.  See references 19 and 21 for examples in [this version of the pdf](https://github.com/greenelab/meta-review/raw/5694085bf4110731665ccbe347d41123f7f463c1/manuscript.pdf).

Is that controlled by or fixable in the CSL file?  It may only affect references that do not have a date.

**Comment by dhimmel** [comment]
> Is that controlled by or fixable in the CSL file? It may only affect references that do not have a date.

Yeah this bugged me too when I was created the revised CSL. I played around a bunch and couldn't find a solution that would always perform appropriate newlines. I can look into a solution. We may have to print "No date", "Date missing", or "In press" as a workaround. Is that acceptable?

In general, when there's no date or other missing metadata, it's because the CSL is incomplete. So generally you should manually override this metadata. But yes, I agree that even with incompete metadata we should provide an aesthetic display.

**Comment by agitter** [comment]
"In press" seems journal-specific, and not a good match for some of the resources we may link to.  "No date" sounds better to me.  Or can we use " " as the default?

Coming up with a placeholder for missing authors is even harder.  It's not that content has "No authors", but rather that we don't know the specific author(s) to attribute sometimes.

**Comment by agitter** [comment]
In the future, we may update the CSL to list book editors when there are no book authors.  See https://github.com/greenelab/meta-review/pull/74

**Comment by agitter** [comment]
Another CSL suggestion from https://github.com/greenelab/manubot-rootstock/pull/132#discussion_r212458417 is to add a default value when there is no author:
> See [meta-review](https://greenelab.github.io/meta-review/v/eb35e87c092a584b8d0bfb4c1f70cda1afb2fc85/#ref-HPKoE9m3) for an example reference without an author. The title and venue are concatenated without whitespace.

The possible solution in https://github.com/greenelab/manubot-rootstock/pull/132#issuecomment-415587496 requires further testing.

**Comment by dhimmel** [comment]
I think we did a good first pass at making an optimal CSL style for modern scholarly publishing. So will close this issue.

There are still some spacing issues which were exposed by looking at all metadata combinations in https://github.com/manubot/manubot/pull/110.
