### ISSUE TITLE
Tracking Manubot usage

### ISSUE THREAD

**Issue by agitter** [manubot/rootstock#67]
It may be nice in the future to produce statistics about how many documents have been authored with Manubot and this rootstock or refer to more examples.  @dhimmel has https://github.com/dhimmel/rephetio-manuscript/ and were examples listed in #62.

I haven't been able to think of a non-invasive way to track this.  Does anyone else have ideas?  Is this worthwhile?

**Comment by dhimmel** [comment]
Agreed. We need a way to search for GitHub repositories that meet a set of criteria. I'm struggling with the online GitHub search to return repos rather than files that meet criteria.

**Comment by agitter** [comment]
I found a [help page](https://help.github.com/articles/searching-repositories/) that shows how to search for terms in a repository's readme.  Searching [`manubot in:readme`](https://github.com/search?utf8=%E2%9C%93&q=manubot+in%3Areadme) works well!

**Comment by dhimmel** [comment]
Nice! 1 false positive (`greenelab/manubot`); 11 true positives.

**Comment by dhimmel** [comment]
@agitter's [search](https://github.com/search?utf8=%E2%9C%93&q=manubot+in%3Areadme) on 2018-03-26 returns 29 repositories. Some interesting manuscripts I hadn't seen before include

+ [Open Data for Climate Policy Research: A review](https://openclimatedata.github.io/open-climate-data-review/)
+ [Introducing yt 3.0: Analysis and Visualization of Volumetric Data](https://github.com/yt-project/yt-3.0-paper)

**Comment by dhimmel** [comment]
Additional instances that appear to currently be in progress are:

+ [Progress Report: Genome-wide hypothesis generation for single-cell expression via latent spaces of deep neural networks](https://greenelab.github.io/czi-hca-report/)
+ [Global Emissions Timeseries](https://openclimatedata.github.io/global-emissions/)

**Comment by dhimmel** [comment]
@agitter's [search](https://github.com/search?utf8=%E2%9C%93&q=manubot+in%3Areadme) on 2018-10-08 returns 40 repositories. Some interesting manuscripts I hadn't seen before include

+ [New plasmids for low-noise gene expression in Escherichia coli](https://zach-hensel.github.io/low-noise-manuscript/)
+ [GimmeMotifs: an analysis framework for transcription factor motif analysis](https://simonvh.github.io/gimmemotifs-manuscript/)
+ [Progress Report: Rapid exploration, interpretation, and comparison of discrete single cell transcriptional basis vectors](http://www.gofflab.org/goff-czi-report/)

**Comment by dhimmel** [comment]
# Manubot Catalog released

We now have a catalog with manuscripts written using Manbuot at https://manubot.org/catalog/. The catalog is defined in the https://github.com/manubot/catalog repository, with CI setup to fetch bibliographic details and trigger deployment.

Going forward, we will add new manuscripts to the catalog rather than commenting on them here.

The GitHub search will still be useful to discover new Manubot manuscripts. Here it is, modified to be ordered by "Recently updated": https://github.com/search?o=desc&q=manubot+in%3Areadme&s=updated&type=Repositories

**Comment by vincerubinetti** [comment]
> @agitter's [search](https://github.com/search?utf8=%E2%9C%93&q=manubot+in%3Areadme) on 2018-10-08 returns 40 repositories

Did we adequately capture all of these in the new catalog @dhimmel ?

**Comment by dhimmel** [comment]
> Did we adequately capture all of these in the new catalog

No, there are some repositories that are really just stubs without much original content. There are also several repositories that are in early stages where I could see the authors wanting to wait to publicize it (OTOH it is public).

Another option would be to add a catalog field like `hidden`. Then we could add every repository to the catalog, while keeping some hidden (at least by default) on manubot.org/catalog. What do you think?

**Comment by vincerubinetti** [comment]
Yeah by "adequately" I meant just the ones that are relatively finished and/or worth putting in the catalog.

I'd be down to put in all of them with a special tag and then another checkbox like "show in progress" or "show stubs".

**Comment by agitter** [comment]
Previously we asked authors before we added their manuscript the to example manuscript list in the Rootstock repository.  Do we want to continue contacting authors before adding manuscripts to the catalog?

The manuscripts are public and easy to find via GitHub search, so we aren't leaking any information by adding them to the catalog.  Nonetheless, I expect some authors would prefer to not have their early stage manuscripts advertised.

**Comment by dhimmel** [comment]
> Do we want to continue contacting authors before adding manuscripts to the catalog?

If an author has advertised a manuscript publicly (or has posted a preprint or published the work), then I think we should add it to the catalog.

Still not sure about in-progress works.

**Comment by agitter** [comment]
Your proposal regarding publicly advertised, preprinted, or published work makes sense to me.

I suggest that we don't include work in progress in the catalog without the authors' permission.

**Comment by agitter** [comment]
I was curious about current usage statistics and ran the Manubot [search](https://github.com/search?o=desc&q=manubot+in%3Areadme&s=updated&type=Repositories) today, sorting by recently updated.  There are now over 20 repos updated in the last week and about 60 updated in the last month.  Many of those are test manuscripts, but it's still a lot of legitimate open writing.

**Comment by agitter** [comment]
The simple GitHub search has false positives (readmes that discuss Manubot but are not manuscripts) and false negatives (manuscripts that use Manubot but have customized readmes or configurations).  Is there a way to search the HTML metadata of the generated manuscript for a unique property like `manubot_html_url_versioned` to improve the quality of our automated searches?  I'm not sure whether search engines index this metadata.

@vincerubinetti do you know?
