### ISSUE TITLE
Deploy with windows generated keys fails

### ISSUE THREAD

**Issue by schliebs** [manubot/rootstock#91]
Ran into a [deploy error](https://travis-ci.org/schliebs/open_manuscript/builds/301423244#L1431) when setting up a manuscript at the OpenCon [doathon](https://github.com/sparcopen/doathon/issues/21):

```
bad decrypt
140040671200928:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:evp_enc.c:520:
```

**Comment by dhimmel** [comment]
Will investigate.

@broadwym got the same issue in https://travis-ci.org/broadwym/manu1/builds/301421591#L1431. Potentially some issue with how the deploy key encryption worked on windows.

**Comment by dhimmel** [comment]
Seems related to https://github.com/travis-ci/travis-ci/issues/4746 and https://github.com/benjcunningham/googlecalendar/issues/2. It looks like its a known issue that `travis encrypt-file` produces files on Windows that fail to decrypt later.

@BanzaiMan locked https://github.com/travis-ci/travis-ci/issues/4746, so its not clear whether Travis intends to fix this issue. This may mean we cannot use `travis encrypt-file` and also support setup on Windows... bummer.

**Comment by agitter** [comment]
It is a lot of overhead, but maybe Docker would work for Windows users?  I successfully ran the Travis encryption inside a Docker container.  But that was tested on an old Linux machine, not Windows.

**Comment by dhimmel** [comment]
From the official [Travis Docs](https://docs.travis-ci.com/user/encrypting-files/#Caveat)

> There is a report of this function not working on a local Windows machine. Please use the WSL (Windows Subsystem for Linux) or a Linux or OS X machine.

So for now, Windows 10+ users should consider using the [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).

**Comment by dhimmel** [comment]
> maybe Docker would work for Windows users?

Yes, I agree!
